FROM python:3.10

RUN pip install pip-tools

COPY ./requirements.txt .
RUN pip-sync requirements.txt
RUN pip install django-debug-toolbar==6.0.0

WORKDIR /usr/src/app

COPY dockerfile_django_dev_entrypoint.sh /dockerfile_django_dev_entrypoint.sh
RUN chmod 755 /dockerfile_django_dev_entrypoint.sh
ENTRYPOINT ["/dockerfile_django_dev_entrypoint.sh"]
