FROM python:3.10

RUN wget https://get.docker.com -q -O /tmp/getdocker && \
    chmod +x /tmp/getdocker && \
    sh /tmp/getdocker

RUN pip install pip-tools

COPY ./requirements.txt .
RUN pip-sync requirements.txt

WORKDIR /usr/src/app

COPY . /usr/src/app
RUN mkdir -p media_root
