FROM python:3.8

RUN wget https://get.docker.com -q -O /tmp/getdocker && \
    chmod +x /tmp/getdocker && \
    sh /tmp/getdocker

RUN pip install pipenv

COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pipenv install --system

WORKDIR /usr/src/app

COPY . /usr/src/app
RUN mkdir -p media_root
