#! /bin/bash
# Requires Ubuntu 14.04

sudo apt-get install -y nginx uwsgi postgresql postgresql-contrib python3-pip python3.4-venv

# Docker installation 
# See: https://docs.docker.com/engine/installation/ubuntulinux/
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo cat "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get purge lxc-docker
sudo apt-cache policy docker-engine
sudo apt-get install linux-image-extra-$(uname -r)
sudo apt-get install -y docker-engine
sudo service docker start
sudo usermod -aG docker $(whoami)
docker run hello-world
docker build -t autograder ./docker-image-setup


# Python setup
mkdir -p $HOME/python_venvs
python3 -m venv $HOME/python_venvs/$1
source $HOME/python_venvs/$1/bin/activate

pip install -r requirements.txt
# Force secrets to be generated by loading django settings module.
python3 manage.py --help > /dev/null


# Database setup
sudo -u postgres createuser -P autograder
echo "Enter the db_password found in autograder/settings/secrets.json"
sudo -u postgres createdb --owner=autograder autograder_db


# Nginx setup
python3 manage.py collectstatic
sudo chmod -R nginx:nginx /home/nginx
sudo mkdir -p /etc/nginx/sites-enabled
sudo cp ./server_config/nginx_autograder.conf /etc/nginx/sites-enabled/

# If /etc/nginx/uwsgi_params doesn't exist, put it there.

# Look here for final steps with uwsgi and nginx config
# https://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html

echo "You must now take the following steps to complete installation:\n"
echo "Run: sudo service nginx start"
echo "Run: uwsgi --ini ./server_config/uwsgi_autograder.ini"
echo "Run: python3 manage.py test --failfast autograder"
