# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 03:03
from __future__ import unicode_literals

import autograder.core.models.ag_model_base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='_DummyForeignAutograderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('one_to_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_models._DummyAutograderModel')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base._AutograderModelMixin, models.Model),
        ),
    ]
