# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='_dummyforeignautogradermodel',
            name='nullable_one_to_one',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nullables', to='test_models._DummyAutograderModel'),
        ),
    ]
