# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='transparent_nullable_foreign_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='...models.DummyForeignAutograderModel'),
        ),
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='transparent_nullable_to_one',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='...models.DummyForeignAutograderModel'),
        ),
    ]
