# Generated by Django 2.0.1 on 2018-05-30 16:55

import autograder.core.fields
import autograder.core.models.ag_model_base
import autograder.core.tests.test_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGModelWithSerializableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('serializable', autograder.core.fields.ValidatedJSONField(serializable_class=autograder.core.tests.test_models.models.DictSerializableClass)),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
    ]
