# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='_dummyautogradermodel',
            name='not_settable_on_create_field',
        ),
    ]
