# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 03:04
from __future__ import unicode_literals

import autograder.core.models.ag_model_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='_DummyToManyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base._AutograderModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='many_to_many',
            field=models.ManyToManyField(to='test_models._DummyToManyModel'),
        ),
    ]
