# Generated by Django 2.0.1 on 2018-06-06 21:21

import autograder.core.fields
import autograder.core.tests.test_models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_agmodelwithserializablefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmodelwithserializablefield',
            name='nullable_serializable',
            field=autograder.core.fields.ValidatedJSONField(blank=True, default=None, null=True, serializable_class=autograder.core.tests.test_models.models.DictSerializableClass),
        ),
    ]
