# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_models', '0002_auto_20160828_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
