# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 18:32
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.tests.test_models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_remove__dummyautogradermodel_not_settable_on_create_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='enum_field',
            field=autograder.core.fields.EnumField(blank=True, default=autograder.core.tests.test_models.models.AnEnum('spam'), enum_type=autograder.core.tests.test_models.models.AnEnum),
        ),
    ]
