# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003__dummyautogradermodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='_dummyautogradermodel',
            name='not_settable_on_create',
            field=models.IntegerField(blank=True, default=77),
        ),
    ]
