# Generated by Django 2.0.1 on 2018-07-30 21:33

import autograder.core.models.ag_model_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003_agmodelwithserializablefield_nullable_serializable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGModelWithDecimalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
    ]
