# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0004__dummyautogradermodel_not_settable_on_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='_dummyautogradermodel',
            old_name='not_settable_on_create',
            new_name='not_settable_on_create_field',
        ),
    ]
