# Generated by Django 2.2.12 on 2020-05-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0004_agmodelwithdecimalfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyautogradermodel',
            name='transparent_foreign_key',
        ),
        migrations.RemoveField(
            model_name='dummyautogradermodel',
            name='transparent_nullable_foreign_key',
        ),
        migrations.RemoveField(
            model_name='dummyautogradermodel',
            name='transparent_nullable_to_one',
        ),
        migrations.RemoveField(
            model_name='dummyautogradermodel',
            name='transparent_to_one',
        ),
    ]
