# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0005_auto_20161118_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='_dummyautogradermodel',
            name='many_to_many',
        ),
        migrations.RemoveField(
            model_name='_dummyautogradermodel',
            name='users',
        ),
        migrations.RemoveField(
            model_name='_dummyforeignautogradermodel',
            name='foreign_key',
        ),
        migrations.RemoveField(
            model_name='_dummyforeignautogradermodel',
            name='nullable_one_to_one',
        ),
        migrations.RemoveField(
            model_name='_dummyforeignautogradermodel',
            name='one_to_one',
        ),
        migrations.DeleteModel(
            name='_DummyAutograderModel',
        ),
        migrations.DeleteModel(
            name='_DummyForeignAutograderModel',
        ),
        migrations.DeleteModel(
            name='_DummyToManyModel',
        ),
    ]
