# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 00:30
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='allow_network_connections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='database_backend_to_use',
            field=autograder.utilities.fields.ShortStringField(blank=True, default=str, max_length=255, strip=True),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='database_name',
            field=autograder.utilities.fields.ShortStringField(blank=True, default=str, max_length=255, strip=True),
        ),
    ]
