# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 19:58
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='interpreter',
            field=autograder.utilities.fields.ShortStringField(blank=True, choices=[('python', 'python'), ('python3', 'python3')], help_text='The interpreter used to run the program.', max_length=255, strip=False),
        ),
    ]
