# Generated by Django 2.0.1 on 2018-04-27 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0003_remove_appliedannotation_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_squashed_0026_rename_io_source_enums'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionGroup',
            new_name='Group',
        ),
    ]
