# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disallow_group_registration',
            field=models.BooleanField(default=False, help_text='A hard override that indicates that students should\n            not be able to send, accept, or reject group\n            invitations.'),
        ),
    ]
