# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:19
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiledautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(blank=True, default='compiled_program', max_length=255, strip=True, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
    ]
