# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_downloadtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agtestsuite',
            name='docker_image_to_use',
        ),
    ]
