# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151215_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledAndRunAutograderTestCase',
            fields=[
                ('compiledautogradertestcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CompiledAutograderTestCase')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.compiledautogradertestcase',),
        ),
    ]
