# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 18:32
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submissiongroupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiongroupinvitation',
            name='_invitees_who_accepted',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
    ]
