# Generated by Django 2.0.1 on 2018-04-27 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_submission_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionGroupInvitation',
            new_name='GroupInvitation',
        ),
    ]
