# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:19
from __future__ import unicode_literals

import autograder.core.models.student_test_suite.student_test_suite_base
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160102_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilationonlyautogradertestcase',
            name='files_to_compile_together',
        ),
        migrations.RemoveField(
            model_name='compiledandrunautogradertestcase',
            name='files_to_compile_together',
        ),
        migrations.AddField(
            model_name='compilationonlyautogradertestcase',
            name='project_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='compilationonlyautogradertestcase',
            name='student_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='compiledandrunautogradertestcase',
            name='project_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='compiledandrunautogradertestcase',
            name='student_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='studenttestsuitebase',
            name='implementation_file_alias',
            field=autograder.utilities.fields.ShortStringField(blank=True, max_length=255, strip=True, validators=[autograder.core.models.student_test_suite.student_test_suite_base._validate_implementation_file_alias]),
        ),
    ]
