# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 02:39
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20151215_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_admins',
            field=models.ManyToManyField(related_name='courses_is_admin_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compilationonlyautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++')], max_length=255, strip=True),
        ),
        migrations.AlterField(
            model_name='compilationonlyautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=True, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='compiledandrunautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++')], max_length=255, strip=True),
        ),
        migrations.AlterField(
            model_name='compiledandrunautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=True, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
    ]
