# Generated by Django 2.0.1 on 2018-04-26 04:08

from django.db import migrations


class FakeEnum:
    def __init__(self, value):
        self.value = value


def rename_io_source_enums(apps, schema_editor):
    AGTestCommand = apps.get_model('core', 'AGTestCommand')
    AGTestCommand.objects.filter(
        stdin_source=FakeEnum('project_file')
    ).update(stdin_source=FakeEnum('instructor_file'))
    AGTestCommand.objects.filter(
        expected_stdout_source=FakeEnum('project_file')
    ).update(expected_stdout_source=FakeEnum('instructor_file'))
    AGTestCommand.objects.filter(
        expected_stderr_source=FakeEnum('project_file')
    ).update(expected_stderr_source=FakeEnum('instructor_file'))


def revert_io_source_enums(apps, schema_editor):
    AGTestCommand = apps.get_model('core', 'AGTestCommand')
    AGTestCommand.objects.filter(
        stdin_source=FakeEnum('instructor_file')
    ).update(stdin_source=FakeEnum('project_file'))
    AGTestCommand.objects.filter(
        expected_stdout_source=FakeEnum('instructor_file')
    ).update(expected_stdout_source=FakeEnum('project_file'))
    AGTestCommand.objects.filter(
        expected_stderr_source=FakeEnum('instructor_file')
    ).update(expected_stderr_source=FakeEnum('project_file'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stdin_from_ag_command'),
    ]

    operations = [
        migrations.RunPython(rename_io_source_enums, reverse_code=revert_io_source_enums)
    ]
