# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 22:49
from __future__ import unicode_literals

import autograder.core.fields
import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_disallow_group_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='valgrind_flags',
            field=autograder.core.fields.StringArrayField(allow_empty_strings=False, blank=True, default=['--leak-check=full', '--error-exitcode=1'], help_text="If use_valgrind is True, this field should contain\n            a list of command line arguments to be passed to the\n            valgrind program.\n            NOTE: This list should NOT contain any\n            details about the program being tested.\n            Example value:\n            ['--leak-check=full', '--error-exitcode=42'] This list can\n            be empty. This list can only be None if use_valgrind is\n            False.\n\n            Default value: ['--leak-check=full', '--error-exitcode=1']\n                if use_valgrind is true, None if use_valgrind is False.\n\n            When ValidationError is raised for this field, the error\n            message will be a list containing strings corresponding (in\n            order) to each flag in this field. The strings will contain\n            an error message for their corresponding flag or be empty if\n            their corresponding flag did not cause an error.", max_string_length=255, null=True, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.+]+$', 32))], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_limit_reset_time',
            field=models.TimeField(default=datetime.time, help_text='The time that marks the beginning and end of the 24\n            hour period during which submissions should be counted\n            towards the daily limit. This value assumes use of the UTC\n            timezone. Defaults to 0:0:0.'),
        ),
    ]
