# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 04:37
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160112_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='database_name',
            field=autograder.utilities.fields.ShortStringField(blank=True, default=str, max_length=255, strip=True, validators=[django.core.validators.RegexValidator('^[a-zA-z]*$')]),
        ),
    ]
