# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160703_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiongroupinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_group_invitations', to='core.Project'),
        ),
    ]
