# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 21:54
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160102_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='_submittedfile',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='_submitted_filenames',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='discarded_files',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.DeleteModel(
            name='_SubmittedFile',
        ),
    ]
