# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 21:01
from __future__ import unicode_literals

import autograder.core.constants
import autograder.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_agtestsuite_docker_image_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestsuite',
            name='docker_image_to_use',
            field=autograder.core.fields.EnumField(default=autograder.core.constants.SupportedImages('default'), enum_type=autograder.core.constants.SupportedImages, help_text='An identifier for the Docker image that the sandbox should be created from.'),
        ),
    ]
