# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 03:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20151216_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='_course_admin_names',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_admins',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='_enrolled_student_names',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='_semester_staff_names',
        ),
        migrations.AddField(
            model_name='course',
            name='_administrator_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(related_name='courses_is_admin_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='semesters_is_enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='staff',
            field=models.ManyToManyField(related_name='semesters_is_staff_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
