# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161004_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiongroup',
            name='extended_due_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When this field is set, it indicates that members\n            of this submission group can submit until this specified\n            date, overriding the project closing time.\n            Default value: None', null=True),
        ),
    ]
