# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 21:50
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autogradertestcasebase_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='entry_point_filename',
            field=autograder.utilities.fields.ShortStringField(blank=True, help_text='The name of a file that should be given to the\n            interpreter as the program to be run, i.e. the main source\n            module.\n            This field is restricted to filenames listed in\n            self.test_resource_files and\n            self.student_resource_files.', max_length=255, strip=False),
        ),
    ]
