# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 01:59
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160704_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_submissions_past_limit',
            field=models.BooleanField(default=True, help_text='Whether to allow additional submissions after a\n            group has submitted num_submissions_per_day times.'),
        ),
        migrations.AddField(
            model_name='project',
            name='num_submissions_per_day',
            field=models.IntegerField(blank=True, default=None, help_text='The number of submissions each group is allowed per\n            day before either reducing feedback or preventing further\n            submissions. A value of None indicates no limit.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_limit_reset_time',
            field=models.TimeField(default=datetime.time, help_text='The time that marks the beginning and end of the 24\n            hour period during which submissions should be counted\n            towards the daily limit. Defaults to 0:0:0'),
        ),
    ]
