# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:19
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160102_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretedAutograderTestCase',
            fields=[
                ('autogradertestcasebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AutograderTestCaseBase')),
                ('compiler', autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=True)),
                ('compiler_flags', autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.]+$', 32))], strip_strings=True)),
                ('project_files_to_compile_together', autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False)),
                ('student_files_to_compile_together', autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False)),
                ('executable_name', autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=True, validators=[autograder.core.shared.utilities.check_user_provided_filename])),
            ],
            options={
                'abstract': False,
            },
            bases=('core.autogradertestcasebase',),
        ),
    ]
