# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20151216_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiongroup',
            name='_members',
        ),
        migrations.AddField(
            model_name='submissiongroup',
            name='members',
            field=models.ManyToManyField(related_name='groups_is_member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
