# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:16
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='studenttestsuitebase',
            name='compile_implementation_files',
        ),
        migrations.RemoveField(
            model_name='studenttestsuitebase',
            name='compiler',
        ),
        migrations.RemoveField(
            model_name='studenttestsuitebase',
            name='compiler_flags',
        ),
        migrations.RemoveField(
            model_name='studenttestsuitebase',
            name='suite_resource_files_to_compile_together',
        ),
        migrations.AddField(
            model_name='compiledstudenttestsuite',
            name='compile_implementation_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compiledstudenttestsuite',
            name='compiler',
            field=models.CharField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], default='g++', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledstudenttestsuite',
            name='compiler_flags',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.]+$', 32))], strip_strings=True),
        ),
        migrations.AddField(
            model_name='compiledstudenttestsuite',
            name='suite_resource_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='compilationonlyautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=True),
        ),
        migrations.AlterField(
            model_name='compiledandrunautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=True),
        ),
    ]
