# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160214_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='database_backend_to_use',
        ),
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='database_name',
        ),
    ]
