# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:24
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interpretedautogradertestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretedautogradertestcase',
            name='entry_point_filename',
            field=autograder.utilities.fields.ShortStringField(default='', max_length=255, strip=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interpretedautogradertestcase',
            name='interpreter',
            field=autograder.utilities.fields.ShortStringField(choices=[('python', 'python'), ('python3', 'python3')], default='', max_length=255, strip=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interpretedautogradertestcase',
            name='interpreter_flags',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.]+$', 32))]),
        ),
    ]
