# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 22:51
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160417_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(blank=True, choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], help_text='The program that will be used to compile the test\n            case executable.', max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(blank=True, help_text='The name of the executable program that should be\n            produced by the compiler. This is the program that will be\n            tested. If empty, the executable will be arbitrarily\n            named.', max_length=255, strip=False),
        ),
    ]
