# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160321_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='process_spawn_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='stack_size_limit',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='virtual_memory_limit',
            field=models.IntegerField(default=500000000),
        ),
    ]
