# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160716_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='num_submissions_per_day',
            new_name='submission_limit_per_day',
        ),
        migrations.AlterField(
            model_name='project',
            name='allow_submissions_past_limit',
            field=models.BooleanField(default=True, help_text='Whether to allow additional submissions after a\n            group has submitted submission_limit_per_day times.'),
        ),
    ]
