# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-13 21:55
from __future__ import unicode_literals

import autograder.core.models.student_test_suite.student_test_suite
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171013_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsuite',
            name='past_limit_submission_fdbk_config',
            field=models.OneToOneField(default=autograder.core.models.student_test_suite.student_test_suite.make_default_past_limit_student_suite_fdbk, help_text='Feedback settings for a Submission that is past the daily limit.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.StudentTestSuiteFeedbackConfig'),
        ),
        migrations.AlterField(
            model_name='studenttestsuitefeedbackconfig',
            name='show_invalid_test_names',
            field=models.BooleanField(default=True, help_text="Whether to show the names of student tests that failed the validity check.\n                     Setting this to true will also include information about whether\n                     invalid test cases exceeded the validity check command's time limit."),
        ),
    ]
