# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:21
from __future__ import unicode_literals

import autograder.core.shared.feedback_configuration
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20151231_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='post_deadline_final_submission_feedback_configuration',
            field=autograder.utilities.fields.JsonSerializableClassField(blank=True, class_=autograder.core.shared.feedback_configuration.AutograderTestCaseFeedbackConfiguration, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studenttestsuitebase',
            name='post_deadline_final_submission_feedback_configuration',
            field=autograder.utilities.fields.JsonSerializableClassField(blank=True, class_=autograder.core.shared.feedback_configuration.StudentTestSuiteFeedbackConfiguration, default=None, null=True),
        ),
    ]
