# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:42
from __future__ import unicode_literals

import autograder.core.shared.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20151231_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsuitebase',
            name='implementation_file_alias',
            field=models.CharField(blank=True, max_length=255, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
    ]
