# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 22:58
from __future__ import unicode_literals

import autograder.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161118_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcaseresult',
            name='error_msg',
            field=models.TextField(blank=True, help_text='If status is "error", an error message will be stored here.'),
        ),
        migrations.AddField(
            model_name='autogradertestcaseresult',
            name='status',
            field=autograder.core.fields.ShortStringField(choices=[('pending', 'pending'), ('grading', 'grading'), ('finished', 'finished'), ('error', 'error')], default='pending', help_text='The grading status of this result.', max_length=255, strip=False),
        ),
        migrations.AlterUniqueTogether(
            name='autogradertestcaseresult',
            unique_together=set([('test_case', 'submission')]),
        ),
    ]
