# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 03:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160322_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='process_spawn_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='stack_size_limit',
            field=models.IntegerField(default=10000000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='virtual_memory_limit',
            field=models.IntegerField(default=500000000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('being_graded', 'Being graded'), ('finished_grading', 'Finished grading'), ('invalid', 'Invalid'), ('error', 'Error'), ('removed_from_queue', 'Removed from queue')], default='received', max_length=255),
        ),
    ]
