# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160103_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretedautogradertestcase',
            name='compiler',
        ),
        migrations.RemoveField(
            model_name='interpretedautogradertestcase',
            name='compiler_flags',
        ),
        migrations.RemoveField(
            model_name='interpretedautogradertestcase',
            name='executable_name',
        ),
        migrations.RemoveField(
            model_name='interpretedautogradertestcase',
            name='project_files_to_compile_together',
        ),
        migrations.RemoveField(
            model_name='interpretedautogradertestcase',
            name='student_files_to_compile_together',
        ),
    ]
