# Generated by Django 2.0.1 on 2018-05-08 20:05

import autograder.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_project_group_invitations_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestsuite',
            name='teardown_suite_cmd',
            field=models.CharField(blank=True, help_text="DEPRECATED. A command to be run after this suite's tests are run.\n                     This command is only run once at the end of the suite.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='teardown_suite_cmd_name',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="DEPRECATED. The name of this suite's teardown command.", max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='discarded_files',
            field=autograder.core.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='The names of files that were discarded when this Submission was created.', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_filenames',
            field=autograder.core.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='The names of files that were submitted, \n                     excluding those that were discarded.', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
    ]
