# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 20:56
from __future__ import unicode_literals

import autograder.core.models.autograder_test_case.autograder_test_case_base
import autograder.core.shared.utilities
import autograder.utilities.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160417_2251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requiredstudentfile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='requiredstudentfile',
            name='project',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='_submitted_filenames',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='invalid_reason_or_error',
        ),
        migrations.AddField(
            model_name='submission',
            name='grading_errors',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, default=list, help_text='A list of errors that occurred while grading this\n            submission', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_filenames',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='The names of submitted_files.', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter',
            field=autograder.utilities.fields.ShortStringField(default='', help_text='The name of the user who made this submission', max_length=255, strip=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='compiler_flags',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='A list of option flags to be passed to the\n            compiler. These flags are limited to the same character set\n            as the command_line_arguments field.\n            NOTE: This list should NOT include the names of files that\n                need to be compiled and should not include flags that\n                affect the name of the resulting executable program.', max_string_length=255, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.+]+$', 32))], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(blank=True, default=autograder.core.models.autograder_test_case.autograder_test_case_base.get_random_executable_name, help_text='The name of the executable program that should be\n            produced by the compiler. This is the program that will be\n            tested.', max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='interpreter_flags',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='A list of objtion flags to be passed to the\n            interpreter. These flags are limited to the same character\n            set as the command_line_argument_field.', max_string_length=255, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.+]+$', 32))], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='max_num_matches',
            field=models.IntegerField(default=1, help_text='The maximum number of submitted student files that\n            can match the pattern. Must be >= min_num_matches'),
        ),
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='min_num_matches',
            field=models.IntegerField(default=1, help_text='The minimum number of submitted student files that\n            should match the pattern. Must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='discarded_files',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='A list of names of files that were discarded when\n            this Submission was created.', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('being_graded', 'being_graded'), ('finished_grading', 'finished_grading'), ('removed_from_queue', 'removed_from_queue'), ('error', 'error')], default='received', help_text='The grading status of this submission see\n            Submission.GradingStatus for details on allowed values.', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_group',
            field=models.ForeignKey(help_text='\n            The SubmissionGroup that this submission belongs to. Note\n            that this field indirectly links this Submission object to a\n            Project.\n            This field is REQUIRED.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.SubmissionGroup'),
        ),
        migrations.AlterField(
            model_name='submissiongroup',
            name='extended_due_date',
            field=models.DateTimeField(blank=True, default=None, help_text='\n            When this field is set, it indicates that members of this\n            submission group can submit until this specified date,\n            overriding the project closing time.\n            Default value: None', null=True),
        ),
        migrations.AlterField(
            model_name='submissiongroup',
            name='members',
            field=models.ManyToManyField(help_text='The Users that belong to this submission group.\n            This list must contain at least one member and no more than\n            project.max_group_size members. A User can only be a member\n            of one submission group per project.\n            This field is REQUIRED.', related_name='groups_is_member_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiongroupinvitation',
            name='_invitees_who_accepted',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='submissiongroupinvitation',
            name='invitation_creator',
            field=models.ForeignKey(help_text='The User who created this invitation.\n            This field is REQUIRED.', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiongroupinvitation',
            name='invited_users',
            field=models.ManyToManyField(help_text='The Users that the invitation_creator has invited\n            to form a submission group together.\n            This field is REQUIRED.\n            This field may not be empty.', related_name='group_invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RequiredStudentFile',
        ),
    ]
