# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160716_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='count_towards_daily_limit',
            field=models.BooleanField(default=True, help_text='Indicates whether this submission should count\n            towards the daily submission limit.'),
        ),
    ]
