# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 21:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160507_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='missing_files',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Stores missing filenames and the additional number\n            of files needed to satisfy a file pattern requirement.\n            Stored as key-value pairs of the form:\n            {pattern: num_additional_needed}'),
        ),
    ]
