# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:59
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20151231_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsuitebase',
            name='implementation_file_alias',
            field=autograder.utilities.fields.ShortStringField(blank=True, max_length=255, strip=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z][a-zA-Z0-9-_.]*$|^$', 32))]),
        ),
    ]
