# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161228_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='grading_errors',
        ),
        migrations.AddField(
            model_name='submission',
            name='error_msg',
            field=models.TextField(blank=True, help_text='If status is "error", an error message will be stored here.'),
        ),
    ]
