# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 19:20
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160103_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretedautogradertestcase',
            name='interpreter_flags',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_=.]+$', 32))], strip_strings=True),
        ),
    ]
