# Generated by Django 2.0.1 on 2018-05-21 18:46

from django.db import migrations, models
import django.db.models.deletion


def set_submission_project_field(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')
    for submission in Submission.objects.select_related('group__project').all():
        submission.project = submission.group.project
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_misc_field_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, default=None,
                                    help_text='A shortcut for submission.group.project.',
                                    null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='submissions', to='core.Project'),
        ),

        migrations.RunPython(set_submission_project_field,
                             reverse_code=lambda apps, schema_editor: None),

        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(help_text='A shortcut for submission.group.project.',
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='submissions', to='core.Project'),
        ),
    ]
