# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 17:54
from __future__ import unicode_literals

import autograder.utilities.fields
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submission_count_towards_daily_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_limit_reset_time',
            field=models.TimeField(default=datetime.time, help_text='The time that marks the beginning and end of the 24\n            hour period during which submissions should be counted\n            towards the daily limit. This value assumes use of the UTC\n            timezone. Defaults to 0:0:0. '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grading_errors',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='A list of errors that occurred while grading this\n            submission', max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='missing_files',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Stores missing filenames and the additional number\n            of files needed to satisfy a file pattern requirement.\n            Stored as key-value pairs of the form:\n            {pattern: num_additional_needed}'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=autograder.utilities.fields.ShortStringField(blank=True, help_text='The name of the user who made this submission', max_length=255, strip=False),
        ),
    ]
