# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161231_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_blank_lines',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_case',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_leading_whitespace',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_newline_changes',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_non_newline_whitespace',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_non_newline_whitespace_changes',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_trailing_whitespace',
            field=models.BooleanField(default=False, help_text='See superdiff.Differ.__init__'),
        ),
    ]
