# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160716_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
