# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 02:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160329_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(help_text='The Users that are administrators for this Course. Administrators have edit access to this Course and its Semesters.', related_name='courses_is_admin_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The name of this course. Must be unique, non-empty and non-null.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
