# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:22
from __future__ import unicode_literals

import autograder.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170103_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='randomly_obfuscated_name_prefix',
            field=autograder.core.fields.ShortStringField(blank=True, default='test', help_text='If a randomly obfuscated name is requested for this\n            test case, that obfuscated name will begin with this\n            value.', max_length=255, strip=False),
        ),
    ]
