# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 03:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160411_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(help_text='The Users that are administrators for\n                  this Course. Administrators have edit access\n                  to this Course and its Semesters.', related_name='courses_is_admin_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The name of this course.\n                  Must be unique, non-empty and non-null.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(help_text='The Course that this semester belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='enrolled_students',
            field=models.ManyToManyField(help_text='Users that are enrolled in this Semester.\n                  Enrolled students can view all visible Projects\n                  associated with this Semester and may be in\n                  SubmissionGroups together.', related_name='semesters_is_enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='The name used to identify this Semester.\n                  Must be non-empty and non-null.\n                  Must be unique among Semesters associated with a\n                  given Course.', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='semester',
            name='staff',
            field=models.ManyToManyField(help_text='Users that are staff members for this Semester.\n            Staff members receive full feedback on autograder test\n            cases and can view student submissions.', related_name='semesters_is_staff_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
