# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 00:16
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160508_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackconfig',
            name='show_return_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='show_stderr_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='show_stdout_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='entry_point_filename',
            field=autograder.utilities.fields.ShortStringField(blank=True, help_text='The name of a file that should be given to the\n            interpreter as the program to be run, i.e. the main source\n            module. It is up to the user to make sure that this file is\n            either a project or student resource file for this test.', max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='compilation_return_code',
            field=models.IntegerField(default=None, help_text='The return code of the command used to compile the\n            program being tested.', null=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='compilation_standard_error_output',
            field=models.TextField(help_text='The contents of the standard error stream of the\n            command used to compile the program being tested.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='compilation_standard_output',
            field=models.TextField(help_text='The contents of the standard output stream of the\n            command used to compile the program being tested.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='return_code',
            field=models.IntegerField(default=None, help_text='The return code of the program that was tested.', null=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='standard_error_output',
            field=models.TextField(help_text='The contents of the standard error stream of the\n            program that was tested.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='standard_output',
            field=models.TextField(help_text='The contents of the standard output stream of the\n            program that was tested.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='submission',
            field=models.ForeignKey(help_text='The submission the test case was run for.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='test_case',
            field=models.ForeignKey(help_text='The test case whose results this object is storing.', on_delete=django.db.models.deletion.CASCADE, to='core.AutograderTestCaseBase'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Whether the program exceeded the time limit.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='valgrind_output',
            field=models.TextField(help_text='The stderr contents of the program valgrind when\n            run against the program being tested.'),
        ),
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='valgrind_return_code',
            field=models.IntegerField(default=None, help_text='The return code of the program valgrind when run\n            against the program being tested.', null=True),
        ),
    ]
