# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 04:08
from __future__ import unicode_literals

import autograder.core.models.student_test_suite.student_test_suite
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171016_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestsuite',
            name='use_setup_command',
            field=models.BooleanField(default=False),
        ),
    ]
