# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 02:13
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160716_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hide_ultimate_submission_fdbk',
            field=models.BooleanField(default=True, help_text='A hard override that indicates that ultimate\n            submission feedback should not be shown, even if the\n            appropriate criteria are met.'),
        ),
        migrations.AddField(
            model_name='project',
            name='ultimate_submission_selection_method',
            field=autograder.utilities.fields.ShortStringField(default='', help_text='The "ultimate" submission for a group is the one\n            that will be used for final grading. This field specifies\n            how the ultimate submission should be determined.', max_length=255, strip=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='disallow_student_submissions',
            field=models.BooleanField(default=False, help_text='A hard override that indicates that students should\n            be prevented from submitting even if visible_to_students is\n            True and it is before closing_time.'),
        ),
    ]
