# Generated by Django 2.0.1 on 2018-05-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180530_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='normal_fdbk_config',
            new_name='old_normal_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='past_limit_submission_fdbk_config',
            new_name='old_past_limit_submission_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='staff_viewer_fdbk_config',
            new_name='old_staff_viewer_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='ultimate_submission_fdbk_config',
            new_name='old_ultimate_submission_fdbk_config',
        ),
    ]
