# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 04:22
from __future__ import unicode_literals

import autograder.core.models.student_test_suite.student_test_suite
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171016_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsuite',
            name='setup_command',
            field=models.OneToOneField(default=autograder.core.models.student_test_suite.student_test_suite.make_default_setup_cmd, help_text="A command to be run after student and project files have\n                     been added to the sandbox but before any other commands are run.\n                     The AGCommand's 'cmd' field must not be blank. To indicate that no\n                     setup command should be run, set use_setup_command to False.", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.AGCommand'),
        ),
    ]
