# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 00:42
from __future__ import unicode_literals

import autograder.core.models.ag_model_base
import autograder.core.models.student_test_suite.student_test_suite_base
import autograder.core.shared.utilities
import autograder.utilities.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160411_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedStudentFilePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', autograder.utilities.fields.ShortStringField(help_text="A shell-style file pattern suitable for\n            use with Python's fnmatch.fnmatch()\n            function (https://docs.python.org/3.4/library/fnmatch.html)\n            This string may contain the same characters allowed in\n            project or student files as well as special pattern\n            matching characters. This string must not be empty.", max_length=255, strip=False)),
                ('min_num_matches', models.IntegerField(help_text='The minimum number of submitted student files that\n            should match the pattern. Must be non-negative.')),
                ('max_num_matches', models.IntegerField(help_text='The maximum number of submitted student files that\n            can match the pattern. Must be >= min_num_matches')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base._AutograderModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='name',
            field=autograder.utilities.fields.ShortStringField(max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='compilationonlyautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='compilationonlyautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='compiledandrunautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='compiledandrunautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=autograder.utilities.fields.ShortStringField(help_text='The name of this course.\n                  Must be unique, non-empty and non-null.', max_length=255, strip=False, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='interpretedautogradertestcase',
            name='entry_point_filename',
            field=autograder.utilities.fields.ShortStringField(max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='interpretedautogradertestcase',
            name='interpreter',
            field=autograder.utilities.fields.ShortStringField(choices=[('python', 'python'), ('python3', 'python3')], max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=autograder.utilities.fields.ShortStringField(help_text='The name used to identify this Semester.\n                  Must be non-empty and non-null.\n                  Must be unique among Semesters associated with a\n                  given Course.', max_length=255, strip=False, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studenttestsuitebase',
            name='implementation_file_alias',
            field=autograder.utilities.fields.ShortStringField(blank=True, max_length=255, strip=False, validators=[autograder.core.models.student_test_suite.student_test_suite_base._validate_implementation_file_alias]),
        ),
    ]
