# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 02:13
from __future__ import unicode_literals

import autograder.core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_autogradertestcasebase_randomly_obfuscated_name_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='ignore_leading_whitespace',
        ),
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='ignore_newline_changes',
        ),
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='ignore_non_newline_whitespace',
        ),
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='ignore_non_newline_whitespace_changes',
        ),
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='ignore_trailing_whitespace',
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_whitespace',
            field=models.BooleanField(default=False, help_text='Ignore inline whitespace when checking output. Equivalent to diff -w'),
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='ignore_whitespace_changes',
            field=models.BooleanField(default=False, help_text='Ignore whitespace changes when checking output. Equivalent to diff -b'),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='expected_standard_error_output',
            field=models.TextField(blank=True, help_text='A string whose contents should be compared to the\n            standard error output of the program being tested. A value\n            of the empty string indicates that this test case should not\n            check the standard error output of the program being\n            tested.', validators=[django.core.validators.MaxLengthValidator(262144)]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='expected_standard_output',
            field=models.TextField(blank=True, help_text='A string whose contents should be compared to the\n            standard output of the program being tested. A value of the\n            empty string indicates that this test case should not check\n            the standard output of the program being tested.', validators=[django.core.validators.MaxLengthValidator(262144)]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='ignore_blank_lines',
            field=models.BooleanField(default=False, help_text='Ignore changes in blank lines when checking output. Equivalent to diff -B'),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='ignore_case',
            field=models.BooleanField(default=False, help_text='Ignore case when checking output. Equivalent to diff -i'),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='interpreter',
            field=autograder.core.fields.ShortStringField(blank=True, choices=[('python', 'python'), ('python3', 'python3'), ('bash', 'bash')], help_text='The interpreter used to run the program.', max_length=255, strip=False),
        ),
    ]
