# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 02:15
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160718_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ultimate_submission_selection_method',
            field=autograder.utilities.fields.ShortStringField(blank=True, choices=[('most_recent', 'most_recent'), ('best_basic_score', 'best_basic_score')], default='most_recent', help_text='The "ultimate" submission for a group is the one\n            that will be used for final grading. This field specifies\n            how the ultimate submission should be determined.', max_length=255, strip=False),
        ),
    ]
