# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160718_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcaseresult',
            name='test_case',
            field=models.ForeignKey(help_text='The test case whose results this object is storing.', on_delete=django.db.models.deletion.CASCADE, related_name='dependent_results', to='core.AutograderTestCaseBase'),
        ),
    ]
