# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 00:46
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='min_num_matches',
            field=models.IntegerField(help_text='The minimum number of submitted student files that\n            should match the pattern. Must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='pattern',
            field=autograder.utilities.fields.ShortStringField(help_text="A shell-style file pattern suitable for\n            use with Python's fnmatch.fnmatch()\n            function (https://docs.python.org/3.4/library/fnmatch.html)\n            This string may contain the same characters allowed in\n            project or student files as well as special pattern\n            matching characters. This string must not be empty.", max_length=255, strip=False, validators=[django.core.validators.RegexValidator(re.compile('[a-zA-Z0-9-_.\\*\\[\\]\\?\\!]+', 32))]),
        ),
        migrations.AlterUniqueTogether(
            name='expectedstudentfilepattern',
            unique_together=set([('pattern', 'project')]),
        ),
    ]
