# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170713_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_truncated',
            field=models.BooleanField(default=False, help_text="Whether the command's stderr was truncated."),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_truncated',
            field=models.BooleanField(default=False, help_text="Whether the command's stdout was truncated."),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stderr_truncated',
            field=models.BooleanField(default=False, help_text="Whether the setup command's stderr was truncated"),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stdout_truncated',
            field=models.BooleanField(default=False, help_text="Whether the setup command's stdout was truncated"),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='teardown_stderr_truncated',
            field=models.BooleanField(default=False, help_text="Whether the teardown command's stderr was truncated"),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='teardown_stdout_truncated',
            field=models.BooleanField(default=False, help_text="Whether the teardown command's stdout was truncated"),
        ),
    ]
