# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 18:03
from __future__ import unicode_literals

import autograder.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170522_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agtestsuite',
            name='setup_suite_cmds',
        ),
        migrations.RemoveField(
            model_name='agtestsuite',
            name='teardown_suite_cmds',
        ),
        migrations.AddField(
            model_name='agtestsuite',
            name='setup_suite_cmd',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="A command to be run before this suite's tests are run.\n                     This command is only run once at the beginning of the suite.\n                     This command will be run after the student and project files\n                     have been added to the sandbox.", max_length=255, strip=False),
        ),
        migrations.AddField(
            model_name='agtestsuite',
            name='teardown_suite_cmd',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="A command to be run after this suite's tests are run.\n                     This command is only run once at the end of the suite.", max_length=255, strip=False),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='teardown_output',
            field=models.TextField(blank=True),
        ),
    ]
