# Generated by Django 2.0.1 on 2018-05-31 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_new_ag_test_suite_fdbk_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestcase',
            old_name='normal_fdbk_config',
            new_name='old_normal_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestcase',
            old_name='past_limit_submission_fdbk_config',
            new_name='old_past_limit_submission_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestcase',
            old_name='staff_viewer_fdbk_config',
            new_name='old_staff_viewer_fdbk_config',
        ),
        migrations.RenameField(
            model_name='agtestcase',
            old_name='ultimate_submission_fdbk_config',
            new_name='old_ultimate_submission_fdbk_config',
        ),
    ]
