# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rerunsubmissionstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cache_is_past_daily_limit',
            field=models.NullBooleanField(default=None, help_text='Whether this submission is past the daily submission limit.\n                     This field is currently nullable for easier integration.'),
        ),
        migrations.AlterField(
            model_name='agcommand',
            name='cmd',
            field=models.CharField(help_text='A string containing the command to be run.\n                     Note: This string will be inserted into [\'bash\', \'-c\', <cmd>]\n                        in order to be executed.\n                     Note: This string defaults to the "true" command\n                     (which does nothing and returns 0) so that AGCommands are\n                     default-creatable.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='cmd',
            field=models.CharField(help_text='A string containing the command to be run.\n                     Note: This string will be inserted into [\'bash\', \'-c\', <cmd>]\n                        in order to be executed.\n                     Note: This string defaults to the "true" command\n                     (which does nothing and returns 0) so that AGCommands are\n                     default-creatable.', max_length=1000),
        ),
    ]
