# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 17:01
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.project.project
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170531_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestsuiteresult',
            name='submission',
            field=models.ForeignKey(help_text='The Submission that this result is for.', on_delete=django.db.models.deletion.CASCADE, related_name='ag_test_suite_results', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ultimate_submission_policy',
            field=autograder.core.fields.EnumField(blank=True, default=autograder.core.models.project.project.UltimateSubmissionPolicy('most_recent'), enum_type=autograder.core.models.project.project.UltimateSubmissionPolicy, help_text='The "ultimate" submission for a group is the one\n            that will be used for final grading. This field specifies\n            how the ultimate submission should be determined.'),
        ),
    ]
