# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170615_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcaseresult',
            name='ag_test_case',
            field=models.ForeignKey(help_text='The AGTestCase that this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='related_ag_test_case_results', to='core.AGTestCase'),
        ),
    ]
