# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 01:22
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.autograder_test_case.autograder_test_case_base
import autograder.core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170522_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='entry_point_filename',
            field=autograder.core.fields.ShortStringField(blank=True, help_text='The name of a file that should be given to the\n            interpreter as the program to be run, i.e. the main source\n            module. It is up to the user to make sure that this file is\n            either a project or student resource file for this test.', max_length=255, strip=False, validators=[autograder.core.utils.check_filename]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='executable_name',
            field=autograder.core.fields.ShortStringField(blank=True, default=autograder.core.models.autograder_test_case.autograder_test_case_base.get_random_executable_name, help_text='The name of the executable program that should be\n            produced by the compiler. This is the program that will be\n            tested.', max_length=255, strip=False, validators=[autograder.core.utils.check_filename]),
        ),
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='pattern',
            field=autograder.core.fields.ShortStringField(help_text="A shell-style file pattern suitable for\n            use with Python's fnmatch.fnmatch()\n            function (https://docs.python.org/3.5/library/fnmatch.html)\n            This string must be a legal UNIX filename and may not be\n            '..' or '.'.\n            NOTE: Patterns for a given project must not overlap,\n                otherwise the behavior is undefined.", max_length=255, strip=False, validators=[autograder.core.utils.check_filename]),
        ),
    ]
