# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 01:52
from __future__ import unicode_literals

import autograder.core.models.ag_model_base
import autograder.utilities.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160417_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredStudentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', autograder.utilities.fields.ShortStringField(max_length=255, strip=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_student_files', to='core.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base._AutograderModelMixin, models.Model),
        ),
    ]
