# Generated by Django 2.0.1 on 2018-05-31 20:47

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_case
from django.db import migrations


# def migrate_ag_test_case_fdbk_configs(apps, schema_editor):
#     AGTestCase = apps.get_model('core', 'AGTestCase')

#     fdbk_field_names = [
#         'normal_fdbk_config',
#         'ultimate_submission_fdbk_config',
#         'past_limit_submission_fdbk_config',
#         'staff_viewer_fdbk_config',
#     ]
#     for case in AGTestCase.objects.all():
#         for field_name in fdbk_field_names:
#             old_field_name = 'old_' + field_name
#             fdbk = {
#                 'visible': getattr(case, old_field_name).visible,
#                 'show_individual_commands': getattr(case, old_field_name).show_individual_commands,
#             }
#             setattr(case, field_name, fdbk)

#         case.full_clean()
#         case.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_ag_test_case_fdbk_conf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcase',
            name='normal_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig, serializable_class=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig),
        ),
        migrations.AddField(
            model_name='agtestcase',
            name='past_limit_submission_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig, serializable_class=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig),
        ),
        migrations.AddField(
            model_name='agtestcase',
            name='staff_viewer_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig, serializable_class=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig),
        ),
        migrations.AddField(
            model_name='agtestcase',
            name='ultimate_submission_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig, serializable_class=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig),
        ),

        # migrations.RunPython(
        #     migrate_ag_test_case_fdbk_configs, lambda apps, schema_editor: None
        # )
    ]
