# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170623_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='cmd',
            field=models.CharField(help_text='A string containing the command to be run.\n                     Note: This string will be split using shlex.split() before it is executed.', max_length=1000),
        ),
    ]
