# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170524_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='feedback_configuration',
            field=models.OneToOneField(blank=True, help_text='Specifies how much information should be included\n            in serialized test case results in normal situations. If not\n            specified, this field is set to a default-constructed\n            FeedbackConfig object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ag_test', to='core.FeedbackConfig'),
        ),
    ]
