# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-04 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171203_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='cache_is_past_daily_limit',
            new_name='is_past_daily_limit',
        ),
    ]
