# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170711_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_limit_reset_timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='The timezone to use when computing how many\n            submissions a group has made in a 24 hour period.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_limit_reset_time',
            field=models.TimeField(default=datetime.time, help_text='The time that marks the beginning and end of the 24\n            hour period during which submissions should be counted\n            towards the daily limit. Defaults to 0:0:0.'),
        ),
    ]
