# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-04 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20171204_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='handgraders',
            field=models.ManyToManyField(help_text='Users that are handgraders for this Course.\n            Handgraders can view best submissions from students\n            and edit the Handgrading Result', related_name='courses_is_handgrader_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
