# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171204_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agtestcaseresult',
            options={'ordering': ('ag_test_case___order',)},
        ),
        migrations.AlterModelOptions(
            name='agtestcommandresult',
            options={'ordering': ('ag_test_command___order',)},
        ),
        migrations.AlterModelOptions(
            name='agtestsuiteresult',
            options={'ordering': ('ag_test_suite___order',)},
        ),
        migrations.AlterModelOptions(
            name='studenttestsuiteresult',
            options={'ordering': ('student_test_suite___order',)},
        ),
    ]
