# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_handgraders'),
        ('core', '0015_auto_20171222_2257'),
    ]

    operations = [
    ]
