# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170508_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='ag_test_case',
            field=models.ForeignKey(blank=True, default=None, help_text='When non-null, indicates that this command belongs to the specified\n                     autograder test.\n                     Either this field or ag_test_suite must be non-null.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ag_test_commands', to='core.AGTestCase'),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='ag_test_suite_is_setup_for',
            field=models.OneToOneField(blank=True, default=None, help_text='When non-null, indicates that this command should be used as the setup\n                     command for the specified suite.\n                     Either this field or ag_test_case must be non-null.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_command', to='core.AGTestSuite'),
        ),
    ]
