# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 22:12
from __future__ import unicode_literals

import autograder.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170711_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestsuite',
            name='setup_suite_cmd_name',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="The name of this suite's setup command.", max_length=255, strip=False),
        ),
        migrations.AddField(
            model_name='agtestsuite',
            name='teardown_suite_cmd_name',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="The name of this suite's teardown command.", max_length=255, strip=False),
        ),
    ]
