# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160417_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='_expected_student_file_patterns',
        ),
        migrations.RemoveField(
            model_name='project',
            name='_required_student_files',
        ),
    ]
