# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170711_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestsuite',
            name='read_only_project_files',
            field=models.BooleanField(default=True, help_text='When True, project files needed for this suite will be read only when this\n                     suite is run.'),
        ),
    ]
