# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160720_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='visible_to_staff_viewer',
        ),
    ]
