# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:35
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_command
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170508_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='stdin_source',
            field=autograder.core.fields.EnumField(choices=[('none', 'none'), ('text', 'text'), ('project_file', 'project_file'), ('setup_stdout', 'setup_stdout'), ('setup_stderr', 'setup_stderr')], default=autograder.core.models.ag_test.ag_test_command.StdinSource('none'), enum_type=autograder.core.models.ag_test.ag_test_command.StdinSource, max_length=255),
        ),
    ]
