# Generated by Django 2.0.1 on 2018-01-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20171222_2323'),
        ('core', '0016_auto_20180102_2305'),
    ]

    operations = [
    ]
