# Generated by Django 2.0.1 on 2018-03-01 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_django_2-0'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiongroup',
            name='_member_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, help_text='A list of usernames of the group members, sorted alphabetically.\n                     This field is updated automatically when self.members is updated\n                     through self.validate_and_update', size=None),
        ),
    ]
