# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_autogradertestcasebase_visible_to_staff_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='deferred',
            field=models.BooleanField(default=False, help_text='A value of True indicates that this test case can\n            be graded asynchronously and that submissions can be marked\n            as finished grading before this test case finishes.'),
        ),
    ]
