# Generated by Django 2.0.1 on 2018-02-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20180102_2338'),
        ('core', '0016_django_2-0'),
    ]

    operations = [
    ]
