# Generated by Django 2.0.1 on 2018-02-27 19:16

from django.db import migrations


def store_member_names(apps, schema_editor):
    SubmissionGroup = apps.get_model('core', 'SubmissionGroup')
    for group in SubmissionGroup.objects.all():
        group._member_names = [user.username for user in group.members.order_by('username').all()]
        group.save()


def clear_member_names(apps, schema_editor):
    SubmissionGroup = apps.get_model('core', 'SubmissionGroup')
    for group in SubmissionGroup.objects.all():
        group._member_names = []
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_submissiongroup__member_names'),
    ]

    operations = [
        migrations.RunPython(store_member_names, reverse_code=clear_member_names)
    ]
