# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:09
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_command
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_agtestcommand_stdin_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='stdin_source',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.StdinSource('none'), enum_type=autograder.core.models.ag_test.ag_test_command.StdinSource),
        ),
        migrations.AlterField(
            model_name='agtestcommandfeedbackconfig',
            name='return_code_fdbk_level',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel('no_feedback'), enum_type=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel),
        ),
        migrations.AlterField(
            model_name='agtestcommandfeedbackconfig',
            name='stderr_fdbk_level',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel('no_feedback'), enum_type=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel),
        ),
        migrations.AlterField(
            model_name='agtestcommandfeedbackconfig',
            name='stdout_fdbk_level',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel('no_feedback'), enum_type=autograder.core.models.ag_test.ag_test_command.ValueFeedbackLevel),
        ),
    ]
