# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_autogradertestcasebase_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='soft_closing_time',
            field=models.DateTimeField(blank=True, default=None, help_text='The date and time that should be displayed as the\n            due date for this project. Unlike closing_time,\n            soft_closing_time does not affect whether submissions are\n            actually accepted.\n            If not None and closing_time is not None, this value must be\n            less than (before) closing_time.', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('being_graded', 'being_graded'), ('waiting_for_deferred', 'waiting_for_deferred'), ('finished_grading', 'finished_grading'), ('removed_from_queue', 'removed_from_queue'), ('error', 'error')], default='received', help_text='The grading status of this submission see\n            Submission.GradingStatus for details on allowed values.', max_length=255),
        ),
    ]
