# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 02:13
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160417_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedstudentfilepattern',
            name='pattern',
            field=autograder.utilities.fields.ShortStringField(help_text="A shell-style file pattern suitable for\n            use with Python's fnmatch.fnmatch()\n            function (https://docs.python.org/3.4/library/fnmatch.html)\n            This string may contain the same characters allowed in\n            project or student files as well as special pattern\n            matching characters. This string must not be empty.", max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_shell_style_file_pattern]),
        ),
    ]
