# Generated by Django 2.0.1 on 2018-03-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_store_member_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissiongroup',
            options={'ordering': ('_member_names',)},
        ),
    ]
