# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:45
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170508_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='stdin_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='stdin_source',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.StdinSource('none'), enum_type=autograder.core.models.ag_test.ag_test_command.StdinSource, help_text='Specifies what kind of source stdin will be redirected from.'),
        ),
    ]
