# Generated by Django 2.0.1 on 2018-06-07 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_first_failure_fdbk_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_submission_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of times a Group can submit to\n            this Project EVER.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='count_towards_total_limit',
            field=models.BooleanField(default=True, help_text='Whether this submission should count towards the total submission limit.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_past_daily_limit',
            field=models.BooleanField(default=False, help_text='Whether this submission is past the daily submission limit.'),
        ),
    ]
