# Generated by Django 2.0.1 on 2018-03-02 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_order_member_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='handgraders',
            field=models.ManyToManyField(help_text='Users that are handgraders for this Course.\n            Handgraders can view best submissions from students\n            and edit the Handgrading Result', related_name='courses_is_handgrader_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
