# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170508_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='stdin_text',
            field=models.TextField(help_text='A string whose contents should be redirected to the stdin of this command.\n                     This value is used when stdin_source is StdinSource.text and is ignored\n                     otherwise.'),
        ),
    ]
