# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:54
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170508_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stderr_source',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ExpectedOutputSource('none'), enum_type=autograder.core.models.ag_test.ag_test_command.ExpectedOutputSource, help_text="Specifies what kind of source this command's stderr should be compared to."),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stderr_text',
            field=models.TextField(default='', help_text="A string whose contents should be compared against this command's stderr.\n                     This value is used when expected_stderr_source is ExpectedOutputSource.text\n                     and is ignored otherwise."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stdout_source',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ExpectedOutputSource('none'), enum_type=autograder.core.models.ag_test.ag_test_command.ExpectedOutputSource, help_text="Specifies what kind of source this command's stdout should be compared to."),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stdout_text',
            field=models.TextField(default='', help_text="A string whose contents should be compared against this command's stdout.\n                     This value is used when expected_stdout_source is ExpectedOutputSource.text\n                     and is ignored otherwise."),
            preserve_default=False,
        ),
    ]
