# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 03:12
from __future__ import unicode_literals

import autograder.core.models.project.uploaded_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20160417_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_obj',
            field=models.FileField(max_length=510, upload_to=autograder.core.models.project.uploaded_file._get_project_file_upload_to_dir, validators=[autograder.core.models.project.uploaded_file._validate_filename]),
        ),
    ]
