# Generated by Django 2.0.1 on 2018-06-08 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_total_submission_limit_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bonus_submissions_remaining',
            field=models.IntegerField(default=0, help_text='The number of bonus submissions this group has left. \n            This field is automatically initialized to self.project.num_bonus_submissions', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='num_bonus_submissions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_bonus_submission',
            field=models.BooleanField(default=False, help_text="When True, indicates that the group that made this \n            submission should be able to request normal feedback for \n            this submission's results.\n            Note: If this field is True, is_past_daily_limit should be \n            False."),
        ),
    ]
