# Generated by Django 2.0.1 on 2018-06-20 16:05

import autograder.core.fields
import autograder.core.models.ag_model_base
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_bonus_submission_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateDaysRemaining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('late_days_remaining', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='num_late_days',
            field=models.IntegerField(default=0, help_text="The number of late days to give to users submitting to this course's projects.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='group',
            name='late_days_used',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Keeps track of how many late days each user in this\n            group has used.\n            Data format: {\n                "<username>": <num late days used>,\n                ...\n            }\n            NOTE: This field is updated only when a group member uses a\n            late day. If a user is moved to another group or this group\n            is merged with another one, this field will NOT be updated.\n        '),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_late_days',
            field=models.BooleanField(default=False, help_text='Whether to allow the use of late days for submitting\n            past the deadline.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='does_not_count_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, help_text='A list of users for whom this submission will NOT\n            count as their final graded submission. Users are added to\n            this list if they are out of late days and another group\n            member (who still has late days remaining) uses their own\n            late day to submit.', size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(help_text='The Users that are admins for this Course.\n                     Admins have edit privileges for this Course.', related_name='courses_is_admin_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=autograder.core.fields.ShortStringField(help_text='The name of this course. Must be unique, non-empty and non-null.', max_length=255, strip=False, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(help_text='Users that are enrolled in this Course.\n                     Enrolled students can view all visible Projects\n                     associated with this Course and may be in\n                     groups together.', related_name='courses_is_enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='bonus_submissions_remaining',
            field=models.IntegerField(help_text='The number of bonus submissions this group has left.\n            This field is automatically initialized to self.project.num_bonus_submissions', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_bonus_submission',
            field=models.BooleanField(default=False, help_text="When True, indicates that the group that made this\n            submission should be able to request normal feedback for\n            this submission's results.\n            Note: If this field is True, is_past_daily_limit should be\n            False."),
        ),
        migrations.AddField(
            model_name='latedaysremaining',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='latedaysremaining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='latedaysremaining',
            unique_together={('course', 'user')},
        ),
    ]
