# Generated by Django 2.0.1 on 2018-04-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_uploaded_file_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpectedStudentFilePattern',
            new_name='ExpectedStudentFile',
        ),
        migrations.AlterField(
            model_name='expectedstudentfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='expected_student_files', to='core.Project'),
        ),
    ]
