# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 17:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170509_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='deduction_for_wrong_return_code',
            field=models.IntegerField(default=0, help_text='The number of points to deduct when this command\n                     produces the wrong return_code (this value must be negative).\n                     Note: The total points given for a single command may be negative,\n                     but the total points for an AGTestCase will be capped at zero.', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='deduction_for_wrong_stderr',
            field=models.IntegerField(default=0, help_text='The number of points to deduct when this command\n                     produces the wrong stderr (this value must be negative).\n                     Note: The total points given for a single command may be negative,\n                     but the total points for an AGTestCase will be capped at zero.', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='deduction_for_wrong_stdout',
            field=models.IntegerField(default=0, help_text='The number of points to deduct when this command\n                     produces the wrong stdout (this value must be negative).\n                     Note: The total points given for a single command may be negative,\n                     but the total points for an AGTestCase will be capped at zero.', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='points_for_correct_return_code',
            field=models.IntegerField(default=0, help_text='The number of points to be awarded when this command\n                     produces the correct return_code', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='points_for_correct_stderr',
            field=models.IntegerField(default=0, help_text='The number of points to be awarded when this command\n                     produces the correct stderr', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='points_for_correct_stdout',
            field=models.IntegerField(default=0, help_text='The number of points to be awarded when this command\n                     produces the correct stdout', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
