# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 03:40
from __future__ import unicode_literals

import autograder.utilities.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160417_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='_uploaded_filenames',
        ),
        migrations.AlterField(
            model_name='project',
            name='allow_submissions_from_non_enrolled_students',
            field=models.BooleanField(default=False, help_text='By default, only staff members and enrolled\n            students for a given Semester can submit to its Projects.\n            When this field is set to True, submissions will be accepted\n            from any authenticated Users, with the following caveats:\n                - In order to view the Project, non-enrolled students\n                must be given a direct link to a page where it can\n                be viewed.\n                - When group work is allowed, non-enrolled students can\n                only be in groups with other non-enrolled students.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='closing_time',
            field=models.DateTimeField(blank=True, default=None, help_text='The date and time that this project should stop\n            accepting submissions.\n            A value of None indicates that this project should\n            stay open.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='disallow_student_submissions',
            field=models.BooleanField(default=False, help_text='A hard override that will prevent\n            students from submitting even if visible_to_students is\n            True and it is before closing_time.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_group_size',
            field=models.IntegerField(default=1, help_text='The maximum number of students that can work in a\n            group on this project.\n            Must be >= 1.\n            Must be >= min_group_size.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_group_size',
            field=models.IntegerField(default=1, help_text='The minimum number of students that can work in a\n            group on this project.\n            Must be >= 1.\n            Must be <= max_group_size.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=autograder.utilities.fields.ShortStringField(help_text='The name used to identify this project.\n            Must be non-empty and non-null.\n            Must be unique among Projects associated with\n            a given semester.\n            This field is REQUIRED.', max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(help_text='The Semester this project belongs to.\n            This field is REQUIRED.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.Semester'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visible_to_students',
            field=models.BooleanField(default=False, help_text='Whether information about this Project can\n            be viewed by students.'),
        ),
    ]
