# Generated by Django 2.0.1 on 2018-07-11 19:33

import autograder.core.fields
import autograder.core.models.course
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_late_day_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', django.db.models.expressions.Case(django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Fall'), then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Winter'), then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Spring'), then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Summer'), then=django.db.models.expressions.Value(4))), 'year')},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=autograder.core.fields.EnumField(blank=True, default=None, enum_type=autograder.core.models.course.Semester, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=autograder.core.fields.ShortStringField(blank=True, help_text='An optional descriptive name for the course.', max_length=255, strip=False),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=autograder.core.fields.ShortStringField(help_text='The name of this course. Must be unique, non-empty and non-null.', max_length=255, strip=False, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='latedaysremaining',
            name='late_days_remaining',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'semester', 'year')},
        ),
    ]
