# Generated by Django 2.0.1 on 2018-04-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_expected_student_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agcommand',
            old_name='stdin_project_file',
            new_name='stdin_instructor_file',
        ),
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='expected_stderr_project_file',
            new_name='expected_stderr_instructor_file',
        ),
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='expected_stdout_project_file',
            new_name='expected_stdout_instructor_file',
        ),
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='stdin_project_file',
            new_name='stdin_instructor_file',
        ),
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='project_files_needed',
            new_name='instructor_files_needed',
        ),
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='read_only_project_files',
            new_name='read_only_instructor_files',
        ),
        migrations.RenameField(
            model_name='studenttestsuite',
            old_name='project_files_needed',
            new_name='instructor_files_needed',
        ),
        migrations.RenameField(
            model_name='studenttestsuite',
            old_name='read_only_project_files',
            new_name='read_only_instructor_files',
        ),
    ]
