# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 17:34
from __future__ import unicode_literals

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_command
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170509_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_return_code',
            field=autograder.core.fields.EnumField(default=autograder.core.models.ag_test.ag_test_command.ExpectedReturnCode('none'), enum_type=autograder.core.models.ag_test.ag_test_command.ExpectedReturnCode, help_text="Specifies the command's expected return code."),
        ),
    ]
