# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 15:19
from __future__ import unicode_literals

import autograder.core.models.ag_model_base
import autograder.utilities.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160417_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_test_name_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('return_code_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('stdout_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('stderr_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('compilation_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('valgrind_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
                ('points_fdbk', autograder.utilities.fields.StringChoiceField(max_length=255, strip=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base._AutograderModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='name',
            field=autograder.utilities.fields.ShortStringField(help_text='The name used to identify this test case.\n            Must be non-empty and non-null.\n            Must be unique among test cases associated with a given\n            project.', max_length=255, strip=False),
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='ag_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.AutograderTestCaseBase'),
        ),
    ]
