# Generated by Django 2.0.1 on 2018-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_course_semester_and_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups_combine_daily_submissions',
            field=models.BooleanField(default=False, help_text='If True, group members can "pool" their daily submissions.\n            For example, if submission_limit_per_day is 3, \n            a group with 2 members would get 6 submissions per day.'),
        ),
    ]
