# Generated by Django 2.0.1 on 2018-04-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_instructor_file_related_fields_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agcommand',
            name='stdin_instructor_file',
        ),
        migrations.RemoveField(
            model_name='agcommand',
            name='stdin_source',
        ),
        migrations.RemoveField(
            model_name='agcommand',
            name='stdin_text',
        ),
    ]
