# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_agtestcommand_expected_return_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stderr_project_file',
            field=models.ForeignKey(blank=True, default=None, help_text="An UploadedFile whose contents should be compared against this command's\n                     stderr. This value is used (and may not be null) when expected_stderr_source\n                     is ExpectedOutputSource.project_file and is ignored otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UploadedFile'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='expected_stdout_project_file',
            field=models.ForeignKey(blank=True, default=None, help_text="An UploadedFile whose contents should be compared against this command's\n                     stdout. This value is used (and may not be null) when expected_stdout_source\n                     is ExpectedOutputSource.project_file and is ignored otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UploadedFile'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='stdin_project_file',
            field=models.ForeignKey(blank=True, default=None, help_text='An UploadedFile whose contents should be redirected to the stdin of this\n                     command. This value is used when stdin_source is StdinSource.project_file\n                     and is ignored otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UploadedFile'),
        ),
    ]
