# Generated by Django 2.0.1 on 2018-07-12 21:04

from django.db import migrations, models


def populate_total_num_subtasks(apps, schema_editor):
    RerunSubmissionsTask = apps.get_model('core', 'RerunSubmissionsTask')

    for task in RerunSubmissionsTask.objects.all():
        task.total_num_subtasks = task.num_completed_subtasks
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_groups_combine_daily_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rerunsubmissionstask',
            name='total_num_subtasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='closing_time',
            field=models.DateTimeField(blank=True, default=None, help_text='The date and time that this project should stop\n            accepting submissions.\n            A value of None indicates that this project should\n            stay open.\n            In the API, this field is hidden from non-admins.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='groups_combine_daily_submissions',
            field=models.BooleanField(default=False, help_text='If True, group members can "pool" their daily submissions.\n            For example, if submission_limit_per_day is 3,\n            a group with 2 members would get 6 submissions per day.'),
        ),

        migrations.RunPython(populate_total_num_subtasks, reverse_code=lambda apps, schema_editor: None),
    ]
