# Generated by Django 2.0.1 on 2018-07-12 21:46

from django.db import migrations, models
import django.utils.timezone


def populate_total_num_subtasks(apps, schema_editor):
    Group = apps.get_model('core', 'Group')

    for group in Group.objects.all():
        group.created_at = group.last_modified
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rerun_submissions_total_num_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
