# Generated by Django 2.0.1 on 2018-07-12 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_group_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bonus_submissions_remaining',
            field=models.IntegerField(blank=True, help_text='The number of bonus submissions this group has left.\n            This field is automatically initialized to self.project.num_bonus_submissions', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
