# Generated by Django 2.0.1 on 2018-07-30 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_fix_course_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestsuite',
            name='points_per_exposed_bug',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The number of points to be awarded per buggy implementation exposed by\n                     the student test cases. This field is limited to 4 digits total and a maximum\n                     of 2 decimal places.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
