# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170516_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestcommandresult',
            old_name='sterr',
            new_name='stderr',
        ),
    ]
