# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170516_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='return_code',
            field=models.IntegerField(blank=True, help_text='The return code of the completed command.'),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stderr',
            field=models.TextField(blank=True, help_text='The stderr contents from running the command.'),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stdout',
            field=models.TextField(blank=True, help_text='The stdout contents from running the command.'),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Whether the program exceeded the time limit.'),
        ),
    ]
