# Generated by Django 2.0.1 on 2018-08-07 20:19

import autograder.core.models.course
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_float_points_per_bug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', 'year', django.db.models.expressions.Case(django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Winter'), then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Spring'), then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Summer'), then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(semester=autograder.core.models.course.Semester('Fall'), then=django.db.models.expressions.Value(4)))), 'permissions': (('create_course', 'Can create new courses and clone courses they are an admin for.'),)},
        ),
    ]
