# Generated by Django 2.0.1 on 2019-01-17 19:16

import autograder.core.fields
from django.conf import settings
from django.db import migrations


def set_preferred_domain(apps, schema_editor):
    Course = apps.get_model('core', 'Course')
    for course in Course.objects.all():
        course.allowed_guest_domain = settings.PREFERRED_DOMAIN
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181117_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_guest_domain',
            field=autograder.core.fields.ShortStringField(blank=True, help_text="When non-empty, indicates that guest users' usernames\n                     must end with this string for them to be allowed access\n                     to projects that allow guests.\n                     When empty, indicates that all guests can access projects\n                     in this course where guests are allowed access.", max_length=255, strip=False),
        ),
        migrations.RunPython(set_preferred_domain)
    ]
