# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170516_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='return_code',
            field=models.IntegerField(default=0, help_text='The return code of the completed command.'),
            preserve_default=False,
        ),
    ]
