# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170516_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agtestcommandresult',
            unique_together=set([('ag_test_command', 'ag_test_case_result')]),
        ),
    ]
