# Generated by Django 2.0.1 on 2019-03-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_ag_test_suite_student_test_suite_sandbox_docker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandboxdockerimage',
            options={'ordering': ('display_name',)},
        ),
    ]
