# Generated by Django 2.0.1 on 2019-03-07 01:13

import autograder.core.constants
import autograder.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_create_sandbox_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestsuite',
            name='sandbox_docker_image',
            field=models.ForeignKey(default='default', help_text='The sandbox docker image to use for running this suite.', on_delete=django.db.models.deletion.PROTECT, to='core.SandboxDockerImage', to_field='name'),
        ),
        migrations.AddField(
            model_name='studenttestsuite',
            name='sandbox_docker_image',
            field=models.ForeignKey(default='default', help_text='The sandbox docker image to use for running this suite.', on_delete=django.db.models.deletion.PROTECT, to='core.SandboxDockerImage', to_field='name'),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='docker_image_to_use',
            field=autograder.core.fields.EnumField(default=autograder.core.constants.SupportedImages('default'), enum_type=autograder.core.constants.SupportedImages, help_text='An identifier for the Docker image that the sandbox should be created from.\n                     This field is DEPRECATED in favor of sandbox_docker_image'),
        ),
        migrations.AlterField(
            model_name='studenttestsuite',
            name='docker_image_to_use',
            field=autograder.core.fields.EnumField(default=autograder.core.constants.SupportedImages('default'), enum_type=autograder.core.constants.SupportedImages, help_text='An identifier for the Docker image that the sandbox should be created from.\n                     This field is DEPRECATED in favor of sandbox_docker_image'),
        ),
    ]
