# Generated by Django 2.0.1 on 2019-03-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sandbox_image_ordering'),
    ]

    operations = [
    ]
