# Generated by Django 2.0.1 on 2019-05-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_set_sandbox_docker_image_foreign_keys'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='normal_fdbk_config',
        #     new_name='old_normal_fdbk_config',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='past_limit_submission_fdbk_config',
        #     new_name='old_past_limit_submission_fdbk_config',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='staff_viewer_fdbk_config',
        #     new_name='old_staff_viewer_fdbk_config',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='ultimate_submission_fdbk_config',
        #     new_name='old_ultimate_submission_fdbk_config',
        # ),
    ]
