# Generated by Django 2.0.1 on 2019-03-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_create_default_sandbox_image'),
    ]

    operations = [
    ]
