# Generated by Django 2.0.1 on 2019-05-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_new_student_test_suite_fdbk_configs'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='get_student_test_names_command',
        #     new_name='old_get_student_test_names_command',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='grade_buggy_impl_command',
        #     new_name='old_grade_buggy_impl_command',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='setup_command',
        #     new_name='old_setup_command',
        # ),
        # migrations.RenameField(
        #     model_name='studenttestsuite',
        #     old_name='student_test_validity_check_command',
        #     new_name='old_student_test_validity_check_command',
        # ),
    ]
