# Generated by Django 2.2 on 2019-06-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190626_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expectedstudentfile',
            options={'ordering': ('pattern',)},
        ),
    ]
