# Generated by Django 2.2 on 2019-06-26 21:23

from django.db import migrations, models


def set_instructor_file_names(apps, schema_editor):
    InstructorFile = apps.get_model('core', 'InstructorFile')
    for file_ in InstructorFile.objects.all():
        file_.name = file_.basename


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_expected_student_file_pattern_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorfile',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='instructorfile',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),

        migrations.RunPython(set_instructor_file_names,
                             reverse_code=lambda apps, schema_editor: None)
    ]
