# Generated by Django 2.2.4 on 2020-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_instructor_file_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='rerunsubmissionstask',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates whether the task has been cancelled by the user.'),
        ),
    ]
