# Generated by Django 2.2.4 on 2020-01-21 20:27

import autograder.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_docker_image_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxdockerimage',
            name='course',
            field=models.ForeignKey(blank=True, default=None, help_text='The course this image is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='sandboxdockerimage',
            name='display_name',
            field=autograder.core.fields.ShortStringField(help_text='A human-readable name for this sandbox image.\n                     This field is required.', max_length=255, strip=False),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxdockerimage',
            unique_together={('display_name', 'course')},
        ),
        migrations.AddField(
            model_name='sandboxdockerimage',
            name='validation_warning',
            field=models.TextField(blank=True, help_text='Warning text from image validation. If empty, then validation succeeded.'),
        ),
    ]
