# Generated by Django 2.2.4 on 2020-01-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rerun_submissions_task_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agtestsuite',
            name='docker_image_to_use',
        ),
        migrations.RemoveField(
            model_name='studenttestsuite',
            name='docker_image_to_use',
        ),
    ]
