# Generated by Django 2.2.4 on 2020-01-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_course_field_to_sandbox_docker_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestsuite',
            old_name='sandbox_docker_image',
            new_name='old_sandbox_docker_image',
        ),
        migrations.RenameField(
            model_name='studenttestsuite',
            old_name='sandbox_docker_image',
            new_name='old_sandbox_docker_image',
        ),
    ]
