# Generated by Django 2.2.4 on 2020-01-21 20:41

from django.db import migrations


def set_updated_sandbox_docker_image_fields(apps, schema_editor):
    AGTestSuite = apps.get_model('core', 'AGTestSuite')
    StudentTestSuite = apps.get_model('core', 'StudentTestSuite')

    for suite in AGTestSuite.objects.all():
        suite.new_sandbox_docker_image = suite.old_sandbox_docker_image
        suite.save()

    for suite in StudentTestSuite.objects.all():
        suite.new_sandbox_docker_image = suite.old_sandbox_docker_image
        suite.save()


def make_course_linked_images(apps, schema_editor):
    SandboxDockerImage = apps.get_model('core', 'SandboxDockerImage')

    images = SandboxDockerImage.objects.exclude(display_name='Default')
    for image in images:
        suites = list(image.studenttestsuite_set.all()) + list(image.agtestsuite_set.all())
        for suite in suites:
            course = suite.project.course
            from_image = suite.sandbox_docker_image
            new_image = SandboxDockerImage.objects.get_or_create(
                display_name=from_image.display_name,
                course=course,
                defaults={
                    'tag': from_image.tag,
                    # We haven't gotten rid of the name field yet, so
                    # we need to generate a unique value to use.
                    'name': from_image.display_name + str(course.pk)
                },
            )[0]
            suite.sandbox_docker_image = new_image
            suite.save()


def delete_course_linked_images(apps, schema_editor):
    SandboxDockerImage = apps.get_model('core', 'SandboxDockerImage')
    SandboxDockerImage.objects.exclude(course=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_change_sandbox_docker_image_related_attr_2'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),

        migrations.RunPython(set_updated_sandbox_docker_image_fields,
                             reverse_code=lambda apps, schema_editor: None),

        migrations.RenameField(
            model_name='agtestsuite',
            old_name='new_sandbox_docker_image',
            new_name='sandbox_docker_image',
        ),
        migrations.RenameField(
            model_name='studenttestsuite',
            old_name='new_sandbox_docker_image',
            new_name='sandbox_docker_image',
        ),

        migrations.RunPython(make_course_linked_images,
                             reverse_code=delete_course_linked_images),

        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
