# Generated by Django 2.2.4 on 2020-03-13 14:49

import autograder.core.fields
import autograder.core.models.ag_model_base
import autograder.core.models.sandbox_docker_image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200210_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSandboxDockerImageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', autograder.core.fields.EnumField(blank=True, default=autograder.core.models.sandbox_docker_image.BuildImageStatus('queued'), enum_type=autograder.core.models.sandbox_docker_image.BuildImageStatus, help_text='The status of the build.')),
                ('filenames', autograder.core.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, help_text='The names of the files uploaded by the user.', max_string_length=255, size=None, string_validators=[], strip_strings=False)),
                ('course', models.ForeignKey(help_text='The course this task is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='build_sandbox_docker_image_tasks', to='core.Course')),
                ('image_to_update', models.ForeignKey(blank=True, default=None, help_text='When null, indicates that a new image will be created.\n            Otherwise, refers to the image to be updated on build success.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SandboxDockerImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
    ]
