# Generated by Django 2.2.4 on 2020-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_build_sandbox_docker_image_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxdockerimage',
            name='tag',
            field=models.TextField(help_text="The full name and tag that can be used to fetch the image\n                     with the 'docker pull' command, e.g. localhost:5001/eecs280:latest."),
        ),
    ]
