# Generated by Django 3.0.5 on 2020-04-22 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_rename_group_invitation_fields_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinvitation',
            old_name='_invitees_who_accepted',
            new_name='_recipients_who_accepted',
        ),
        migrations.RenameField(
            model_name='groupinvitation',
            old_name='invitation_creator',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='recipients',
            field=models.ManyToManyField(help_text='The Users that the sender has invited\n            to form a submission group together.\n            This field is REQUIRED.\n            This field may not be empty.', related_name='group_invitations_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
