# Generated by Django 3.0.5 on 2020-04-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rename_group_invitation_fields_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
