# Generated by Django 3.0.5 on 2020-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='use_virtual_memory_limit',
            field=models.BooleanField(blank=True, default=True, help_text='When set to false, the virtual memory limit will not\n            be applied to the command. Note that the sandbox will still apply\n            a physical memory limit to all commands run in the sandbox.'),
        ),
    ]
