# Generated by Django 3.0.5 on 2020-04-29 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_limit_virtual_memory_bool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='bonus_submissions_remaining',
            new_name='old_bonus_submissions_remaining',
        ),
        migrations.AddField(
            model_name='group',
            name='bonus_submissions_used',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='group',
            name='_extra_bonus_submissions_granted',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
