# Generated by Django 3.0.5 on 2020-04-29 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_bonus_submission_rework_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='old_bonus_submissions_remaining',
            field=models.IntegerField(blank=True, default=0, help_text='The number of bonus submissions this group has left.\n            This field is automatically initialized to self.project.num_bonus_submissions', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
