# Generated by Django 3.0.5 on 2020-04-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_bonus_submission_rework_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latedaysremaining',
            old_name='late_days_remaining',
            new_name='old_late_days_remaining',
        ),
    ]
