# Generated by Django 3.0.5 on 2020-04-29 19:09

import django.core.validators
from django.db import migrations, models


def migrate_late_day_totals(apps, schema_editor):
    LateDaysRemaining = apps.get_model('core', 'LateDaysRemaining')
    for obj in LateDaysRemaining.objects.all():
        obj.late_days_remaining = obj.old_late_days_remaining
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_late_day_rework_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='latedaysremaining',
            name='_extra_late_days_granted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='latedaysremaining',
            name='late_days_used',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='latedaysremaining',
            name='old_late_days_remaining',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),

        migrations.RunPython(
            migrate_late_day_totals, reverse_code=lambda apps, schema_editor: None),
    ]
