# Generated by Django 3.0.5 on 2020-05-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_rename_mutation_test_suite_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutationtestsuiteresult',
            options={'ordering': ('mutation_test_suite___order',)},
        ),
        migrations.RenameField(
            model_name='mutationtestsuiteresult',
            old_name='student_test_suite',
            new_name='mutation_test_suite',
        ),
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='project',
            field=models.ForeignKey(help_text='The Project that this student test suite belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mutation_test_suites', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_test_suite_results', to='core.Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='mutationtestsuiteresult',
            unique_together={('mutation_test_suite', 'submission')},
        ),
    ]
