# Generated by Django 3.0.5 on 2020-05-05 14:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_rename_mutation_test_suite_fields_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='deferred',
            field=models.BooleanField(default=False, help_text='If true, this mutation test suite can be graded asynchronously.\n                     Deferred suites that have yet to be graded do not prevent members\n                     of a group from submitting again.'),
        ),
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='project',
            field=models.ForeignKey(help_text='The Project that this mutation test suite belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mutation_test_suites', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='rerunsubmissionstask',
            name='mutation_suite_pks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='When rerun_all_mutation_test_suites is False, specifies which\n                     mutation test suites should be rerun.', size=None),
        ),
        migrations.AlterField(
            model_name='rerunsubmissionstask',
            name='rerun_all_mutation_test_suites',
            field=models.BooleanField(default=True, help_text='When True, indicates that all MutationTestSuites belonging\n                     to the specified project should be rerun. Otherwise,\n                     only the MutationTestSuites specified in mutation_test_suite_pks\n                     should be rerun.'),
        ),
    ]
