# Generated by Django 2.2.12 on 2020-05-13 15:26

import django.core.validators
from django.db import migrations, models


def migrate_process_spawn_limit(apps, schema_editor):
    AGTestCommand = apps.get_model('core', 'AGTestCommand')
    MutationTestSuite = apps.get_model('core', 'MutationTestSuite')
    for cmd in AGTestCommand.objects.all():
        if cmd.process_spawn_limit == 0:
            cmd.block_process_spawn = True
            cmd.save()

    for suite in MutationTestSuite.objects.all():
        suite.setup_command.block_process_spawn = (
            suite.setup_command.process_spawn_limit == 0)
        suite.get_student_test_names_command.block_process_spawn = (
            suite.get_student_test_names_command.process_spawn_limit == 0)
        suite.student_test_validity_check_command.block_process_spawn = (
            suite.student_test_validity_check_command.process_spawn_limit == 0)
        suite.grade_buggy_impl_command.block_process_spawn = (
            suite.grade_buggy_impl_command.process_spawn_limit == 0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_rename_mutation_test_suite_fields_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='block_process_spawn',
            field=models.BooleanField(blank=True, default=False, help_text='When true, prevents the command from spawning child processes.'),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='process_spawn_limit',
            field=models.IntegerField(default=0, help_text="DEPRECATED. Use block_process_spawn instead.\n            The maximum number of processes that the command is allowed to spawn.\n            Must be >= 0\n            Must be <= 150\n            NOTE: This limit applies cumulatively to the processes\n                  spawned by the main program being run. i.e. If a\n                  spawned process spawns it's own child process, both\n                  of those processes will count towards the main\n                  program's process limit.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.RunPython(
            migrate_process_spawn_limit, reverse_code=lambda apps, schema_editor: None),
    ]
