# Generated by Django 2.2.12 on 2020-05-13 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_add_block_process_spawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='process_spawn_limit',
            field=models.IntegerField(default=0, help_text="This field is IGNORED and will be removed in version 5.0.0.\n            Use block_process_spawn instead.\n\n            The maximum number of processes that the command is allowed to spawn.\n            Must be >= 0\n            Must be <= 150\n            NOTE: This limit applies cumulatively to the processes\n                  spawned by the main program being run. i.e. If a\n                  spawned process spawns it's own child process, both\n                  of those processes will count towards the main\n                  program's process limit.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='stack_size_limit',
            field=models.IntegerField(default=10000000, help_text='This field is IGNORED and will be removed in version 5.0.0.\n            The maximum stack size in bytes.\n            Must be > 0\n            Must be <= 100000000\n            NOTE: Setting this value too low may cause the command to crash prematurely.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
