# Generated by Django 2.2.12 on 2020-05-14 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200513_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='virtual_memory_limit',
            field=models.BigIntegerField(default=500000000, help_text='The maximum amount of virtual memory\n            (in bytes) the command can use. Must be > 0.\n            Limiting virtual memory can help produce cleaner\n            error messages when the command uses too much memory. However, some programs allocate\n            a large amount of virtual memory but use very little *physical* memory. For these\n            kinds of programs (e.g. Java programs), we recommend NOT limiting virtual memory.\n            Note that physical memory usage will still be limited for security reasons.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
