# Generated by Django 2.2.12 on 2020-05-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_virtual_memory_limit_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rerunsubmissionstask',
            name='celery_group_result_id',
        ),
    ]
