# Generated by Django 2.2.12 on 2020-06-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_rerun_celery_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildsandboxdockerimagetask',
            old_name='image_to_update',
            new_name='image',
        ),
    ]
