# Generated by Django 2.2.12 on 2020-06-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_rename_image_to_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsandboxdockerimagetask',
            name='image',
            field=models.ForeignKey(blank=True, default=None, help_text='When initially null, indicates that a new image will be created.\n            That new image will then be set as the value for this field.\n\n            When not null initially, indicates that the specified image\n            should be updated when the build finishes.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SandboxDockerImage'),
        ),
    ]
