# Generated by Django 2.2.12 on 2020-06-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_image_build_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildsandboxdockerimagetask',
            options={'ordering': ['-pk']},
        ),
    ]
