# Generated by Django 2.2.12 on 2020-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_image_build_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='use_virtual_memory_limit',
            field=models.BooleanField(blank=True, default=False, help_text='When set to false, the virtual memory limit will not\n            be applied to the command. Note that the sandbox will still apply\n            a physical memory limit to all commands run in the sandbox.'),
        ),
    ]
