# Generated by Django 2.2.12 on 2020-07-09 16:47

import autograder.core.fields
import autograder.core.models.mutation_test_suite.mutation_test_suite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_change_use_virtual_mem_limit_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='staff_viewer_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.mutation_test_suite.mutation_test_suite.MutationTestSuiteFeedbackConfig.default_staff_viewer_fdbk_config, help_text='Feedback settings for a staff member viewing a Submission from another group.', serializable_class=autograder.core.models.mutation_test_suite.mutation_test_suite.MutationTestSuiteFeedbackConfig),
        ),
    ]
