# Generated by Django 3.1 on 2020-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_honor_pledge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestsuite',
            name='reject_submission_if_setup_fails',
            field=models.BooleanField(default=False, help_text='When this field is True and the suite has a setup command,\n            the submission will be rejected if that setup command fails.\n            This field is only allowed to be True for the first AGTestSuite\n            (order specified by Project.get_agtestsuite_order()) of the Project.\n        '),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='setup_suite_cmd',
            field=models.CharField(blank=True, help_text="A command to be run before this suite's tests are run.\n                     This command is only run once at the beginning of the suite.\n                     This command will be run after the student and project files\n                     have been added to the sandbox.\n                     If this field is empty, then no setup command will be run.", max_length=1000),
        ),
    ]
