# Generated by Django 3.1 on 2020-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_reject_submission_if_setup_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grading_start_time',
            field=models.DateTimeField(blank=True, default=None, help_text='The time that the submission was marked as being_graded.Can be used to calculate time spent in queue.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='non_deferred_grading_end_time',
            field=models.DateTimeField(blank=True, default=None, help_text='The time that the submission was marked as waiting_for_deferred.Can be used to calculate time spent grading non-deferred tests.', null=True),
        ),
    ]
