# Generated by Django 3.1 on 2020-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_submission_grading_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestsuite',
            name='reject_submission_if_setup_fails',
            field=models.BooleanField(default=False, help_text='When this field is True and the suite has a setup command,\n            the submission will be rejected if that setup command fails.\n            This field is only allowed to be True for the first non-deferred AGTestSuite\n            (order specified by Project.get_agtestsuite_order()) of the Project.\n        '),
        ),
    ]
