# Generated by Django 3.1.2 on 2020-10-28 16:08

import autograder.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20200924_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcase',
            name='name',
            field=models.CharField(help_text='The name used to identify this autograder test.\n                     Must be non-empty and non-null.\n                     Must be unique among autograder tests that belong to the same suite.\n                     This field is REQUIRED.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agtestcommand',
            name='name',
            field=models.CharField(help_text='The name used to identify this command.\n                         Must be non-empty and non-null.\n                         Must be unique among commands that belong to the same autograder test.\n                         This field is REQUIRED.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='name',
            field=models.CharField(help_text='The name used to identify this suite.\n                     Must be non-empty and non-null.\n                     Must be unique among suites that belong to the same project.\n                     This field is REQUIRED.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='setup_suite_cmd_name',
            field=models.CharField(blank=True, help_text="The name of this suite's setup command.", max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_guest_domain',
            field=models.CharField(blank=True, help_text="When non-empty, indicates that guest users' usernames\n                     must end with this string for them to be allowed access\n                     to projects that allow guests.\n                     When empty, indicates that all guests can access projects\n                     in this course where guests are allowed access.", max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The name of this course. Must be unique, non-empty and non-null.', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, help_text='An optional descriptive name for the course.', max_length=255),
        ),
        migrations.AlterField(
            model_name='expectedstudentfile',
            name='pattern',
            field=models.CharField(help_text="A shell-style file pattern suitable for\n            use with Python's fnmatch.fnmatch()\n            function (https://docs.python.org/3.5/library/fnmatch.html)\n            This string must be a legal UNIX filename and may not be\n            '..' or '.'.\n            NOTE: Patterns for a given project must not overlap,\n                otherwise the behavior is undefined.", max_length=255, validators=[autograder.core.utils.check_filename]),
        ),
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='name',
            field=models.CharField(help_text='The name used to identify this MutationTestSuite.\n                     Must be non-empty and non-null.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The name used to identify this project.\n            Must be non-empty and non-null.\n            Must be unique among Projects associated with\n            a given course.\n            This field is REQUIRED.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sandboxdockerimage',
            name='display_name',
            field=models.CharField(help_text='A human-readable name for this sandbox image.\n                     Must be unique among images belonging to a course.\n                     This field is required.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sandboxdockerimage',
            name='name',
            field=models.CharField(help_text='A string uniquely identifying this sandbox image.\n                     This field is required and cannot be edited after\n                     creation.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.CharField(blank=True, help_text='The name of the user who made this submission', max_length=255),
        ),
    ]
