# Generated by Django 3.1.2 on 2020-10-28 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_replace_short_string_field_with_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsandboxdockerimagetask',
            name='filenames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of the files uploaded by the user.', size=None),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='_recipients_who_accepted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='buggy_impl_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of buggy implementations that student tests should be run against.', size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='bugs_exposed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="The names of instructor buggy implementations that were exposed\n                     by the student's test cases.", size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='discarded_tests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='"The names of student tests that were discarded due\n                      to too many tests being discovered.', size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='invalid_tests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of student test cases that failed the validity check.', size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='student_tests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of discovered student test cases.', size=None),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='timed_out_tests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of student test cases that timed out during the validity check.', size=None),
        ),
        migrations.AlterField(
            model_name='submission',
            name='discarded_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of files that were discarded when this Submission was created.', size=None),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_filenames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='The names of files that were submitted,\n                     excluding those that were discarded.', size=None),
        ),
    ]
