# Generated by Django 3.1.2 on 2020-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_replace_enum_field_with_text_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('being_graded', 'Being Graded'), ('waiting_for_deferred', 'Waiting For Deferred'), ('finished_grading', 'Finished Grading'), ('removed_from_queue', 'Removed From Queue'), ('rejected', 'Rejected'), ('error', 'Error')], default='received', help_text='The grading status of this submission see\n            Submission.GradingStatus for details on allowed values.', max_length=255),
        ),
    ]
