# Generated by Django 2.2.18 on 2021-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20201111_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_submissions_past_extension',
            field=models.BooleanField(blank=True, default=False, help_text="When True, 'extended_due_date' is treated as a soft\n            deadline, and the group can continue submitting after\n            'extended_due_date' has passed.\n        "),
        ),
    ]
