# Generated by Django 3.2.2 on 2021-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20201111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='return_code_correct',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stderr_correct',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stdout_correct',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='late_days_used',
            field=models.JSONField(blank=True, default=dict, help_text='Keeps track of how many late days each user in this\n            group has used.\n            Data format: {\n                "\\<username\\>": \\<num late days used\\>,\n                ...\n            }\n            NOTE: This field is updated only when a group member uses a\n            late day. If a user is moved to another group or this group\n            is merged with another one, this field will NOT be updated.\n        '),
        ),
        migrations.AlterField(
            model_name='rerunsubmissionstask',
            name='ag_test_suite_data',
            field=models.JSONField(blank=True, default=dict, help_text='When rerun_all_ag_test_suites is False, specifies which\n                     AGTestSuites should be rerun and which AGTestCases within\n                     those suites should be rerun.\n\n        Data format:\n        {\n            // Note: JSON format requires that keys are strings. Postgres\n            // doesn\'t seem to care, but some JSON serializers might.\n            "<ag_test_suite_pk>": [<ag_test_case_pk>, ...],\n            ...\n        }\n\n        If an ag_test_suite_pk is mapped to an empty list, then all ag test cases\n        belonging to that ag test suite will be rerun.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='denormalized_ag_test_results',
            field=models.JSONField(blank=True, default=dict, help_text='Stores denormalized AG test results in order to avoid\n                     expensive joins when getting submission result feedback.\n                     To update this field, use\n                     autograder.core.submission_feedback.update_denormalized_ag_test_results\n\n                     Data format:\n{\n    "<ag test suite pk>": {\n        <ag test suite result data>,\n        "ag_test_case_results": {\n            "<ag test case pk>": {\n                <ag test case result data>,\n                "ag_test_command_results": {\n                    "<ag test command pk>": <ag test command result data>\n                }\n            }\n        }\n    }\n}\n        '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='missing_files',
            field=models.JSONField(blank=True, default=dict, help_text='Stores missing filenames and the additional number\n            of files needed to satisfy a file pattern requirement.\n            Stored as key-value pairs of the form:\n            {pattern: num_additional_needed}'),
        ),
    ]
