# Generated by Django 3.2.2 on 2021-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20210506_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='return_code_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stderr_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stdout_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
