# Generated by Django 3.2.2 on 2022-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_timezone_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='include_pending_extensions',
            field=models.BooleanField(default=False, help_text='Applies only to "final_graded_submission_scores" downloads,\n            ignored otherwise. When True, students with pending extensions will be\n            included in final_graded_submission_scores download CSV files.'),
        ),
    ]
