# Generated by Django 3.2.2 on 2022-04-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_downloadtask_include_pending_extensions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorfile',
            old_name='file_obj',
            new_name='_remove_in_v5_file_obj',
        ),
    ]
