# Generated by Django 3.2.2 on 2022-11-30 20:33

import autograder.core.fields
import autograder.core.models.ag_command.command
import autograder.core.models.mutation_test_suite.mutation_test_suite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_test_name_discovery_whitespace_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtestsuite',
            name='get_student_test_names_command',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.mutation_test_suite.mutation_test_suite.new_make_default_get_student_test_names_cmd, help_text="This required command should print out a list of student\n             test case names. The test case names should not be wrapped\n             in quotes, even if the test names contain spaces.\n             If test_name_discovery_whitespace_handling is set to\n             'any_whitespace', the output of this command will be parsed using\n             Python's str.split(). If set to 'newline', the output will\n             be parsed using Python's str.splitlines(), and leading and trailing\n             whitespace will be stripped from each line.", serializable_class=autograder.core.models.ag_command.command.Command),
        ),
    ]
