# Generated by Django 3.2.2 on 2024-01-29 20:21

import autograder.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_project_submission_limit_reset_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_limit_reset_timezone',
            field=models.TextField(default='UTC', help_text='A string representing the timezone to use when computing\n            how many submissions a group has made in a 24 hour period.', validators=[autograder.core.utils.validate_timezone]),
        ),
    ]
