# Generated by Django 5.2.4 on 2025-08-13 16:07

import autograder.core.models.ag_model_base
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0109_auto_20250225_1535'), ('core', '0110_auto_20250306_1722'), ('core', '0111_auto_20250401_2000'), ('core', '0112_alter_agtestcommandresult_partial_credit_points'), ('core', '0113_agtestcommandresult_custom_scoring_used'), ('core', '0114_agtestcommand_custom_scoring_description'), ('core', '0115_auto_20250516_0238'), ('core', '0116_auto_20250619_1341'), ('core', '0117_output_size_fields'), ('core', '0118_submission__output_migrated'), ('core', '0119_alter_agtestcommandresult_stderr_size_and_more'), ('core', '0120_agtestcommandresult_stderr_diff_size_and_more'), ('core', '0121_alter_agtestcommandresult_stderr_diff_size_and_more'), ('core', '0117_latedayusage'), ('core', '0122_merge_20250801_1924')]

    dependencies = [
        ('core', '0108_internal_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='custom_scoring_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='custom_scoring_label',
            field=models.TextField(blank=True, default=None, help_text='An optional label for custom scoring points', null=True),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='custom_scoring_regex',
            field=models.TextField(default='(?i)<!!\\s*score:\\s*(-?\\d+)\\s*!!>', help_text='Specifies the regex pattern used to extract the partial credit\n                     score from the output stream'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='custom_scoring_source',
            field=models.TextField(choices=[('none', 'None'), ('stdout', 'Stdout'), ('stderr', 'Stderr')], default='none', help_text='Specifies the output stream where partial credit output will be\n                     printed to. Note that stdout cannot be selected when\n                     expected_stdout_source is not none, and stderr cannot be selected\n                     when expected_stderr_source is not none'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='max_points_for_custom_scoring',
            field=models.IntegerField(default=0, help_text='The maximum number of points that can be awarded when using\n                     partial credit scoring', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='custom_scoring_error',
            field=models.TextField(choices=[('none', 'None'), ('non_integer', 'Non Integer'), ('exceeded_max_points', 'Exceeded Max Points'), ('failed_to_find_pattern', 'Failed To Find Pattern')], default='none'),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='custom_scoring_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='_output_migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using gzip: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using gzip: https://docs.python.org/3/library/gzep.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='get_student_test_names_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stderr.\n            None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='get_student_test_names_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stdout.\n            None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0.\n            The size in bytes of the diff result for this stderr.\n            When None, fall back to the previous logic for computing diff size.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0.\n            The size in bytes of the diff result for this stdout.\n            When None, fall back to the previous logic for computing diff size.\n        ', null=True),
        ),
        migrations.CreateModel(
            name='LateDayUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_pk', models.IntegerField()),
                ('group_pk', models.IntegerField()),
                ('project_pk', models.IntegerField()),
                ('submission_pk', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('num_late_days_used', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
    ]

