# Generated by Django 3.2.25 on 2025-02-25 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_internal_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='max_points_for_partial_credit',
            field=models.IntegerField(default=0, help_text='The maximum number of points that can be awarded when using\n                     partial credit scoring', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='partial_credit_regex',
            field=models.TextField(default='<!! score: (-?\\d+) !!>', help_text='Specifies the regex pattern used to extract the partial credit\n                     score from the output stream'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='partial_credit_source',
            field=models.TextField(choices=[('none', 'None'), ('stdout', 'Stdout'), ('stderr', 'Stderr')], default='none', help_text='Specifies the output stream where partial credit output will be\n                     printed to. Note that stdout cannot be selected when\n                     expected_stdout_source is not none, and stderr cannot be selected\n                     when expected_stderr_source is not none'),
        ),
    ]
