# Generated by Django 3.2.25 on 2025-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20250225_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='partial_credit_error',
            field=models.TextField(choices=[('none', 'None'), ('non_integer', 'Non Integer'), ('pattern_not_found', 'Pattern Not Found')], default='none'),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='partial_credit_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
