# Generated by Django 3.2.25 on 2025-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20250306_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommand',
            name='custom_scoring_regex',
            field=models.TextField(default='(?i)<!!\\s*score:\\s*(-?\\d+)\\s*!!>', help_text='Specifies the regex pattern used to extract the partial credit\n                     score from the output stream'),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='custom_scoring_error',
            field=models.TextField(choices=[('none', 'None'), ('non_integer', 'Non Integer'), ('exceeded_max_points', 'Exceeded Max Points'), ('failed_to_find_pattern', 'Failed To Find Pattern')], default='none'),
        ),
    ]
