# Generated by Django 3.2.25 on 2025-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20250401_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='partial_credit_points',
            field=models.IntegerField(default=0),
        ),
    ]
