# Generated by Django 3.2.25 on 2025-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_agtestcommandresult_partial_credit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='custom_scoring_used',
            field=models.BooleanField(default=False),
        ),
    ]
