# Generated by Django 3.2.25 on 2025-05-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_agtestcommandresult_custom_scoring_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommand',
            name='custom_scoring_description',
            field=models.TextField(blank=True, default=None, help_text='An optional description for custom scoring points', null=True),
        ),
    ]
