# Generated by Django 3.2.25 on 2025-05-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_agtestcommand_custom_scoring_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agtestcommand',
            name='custom_scoring_description',
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='custom_scoring_label',
            field=models.TextField(blank=True, default=None, help_text='An optional label for custom scoring points', null=True),
        ),
    ]
