# Generated by Django 3.2.25 on 2025-06-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20250516_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='partial_credit_regex',
            new_name='custom_scoring_regex',
        ),
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='partial_credit_source',
            new_name='custom_scoring_source',
        ),
        migrations.RenameField(
            model_name='agtestcommand',
            old_name='max_points_for_partial_credit',
            new_name='max_points_for_custom_scoring',
        ),
        migrations.RenameField(
            model_name='agtestcommandresult',
            old_name='partial_credit_error',
            new_name='custom_scoring_error',
        ),
        migrations.RenameField(
            model_name='agtestcommandresult',
            old_name='partial_credit_points',
            new_name='custom_scoring_points',
        ),
    ]
