# Generated by Django 3.2.25 on 2025-07-10 05:47

import autograder.core.models.ag_model_base
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20250619_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateDayUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_pk', models.IntegerField()),
                ('group_pk', models.IntegerField()),
                ('project_pk', models.IntegerField()),
                ('submission_pks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('timestamp', models.DateTimeField()),
                ('num_late_days_used', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
            options={
                'abstract': False,
            },
            bases=(autograder.core.models.ag_model_base.ToDictMixin, models.Model),
        ),
    ]
