# Generated by Django 3.2.25 on 2025-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20250619_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stdout", null=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stdout", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stdout", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stderr", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stdout", null=True),
        ),
    ]
