# Generated by Django 5.2.4 on 2025-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20250619_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='agtestsuiteresult',
            name='setup_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='grade_buggy_impls_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the grade buggy impls command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='setup_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the setup command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AddField(
            model_name='mutationtestsuiteresult',
            name='validity_check_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the validity check command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
    ]
