# Generated by Django 5.2.4 on 2025-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_output_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='_output_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
