# Generated by Django 5.2.4 on 2025-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_submission__output_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stderr. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using gzip: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the command's stdout. None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using gzip: https://docs.python.org/3/library/gzep.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stderr_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stderr.\n            None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
        migrations.AlterField(
            model_name='mutationtestsuiteresult',
            name='student_test_names_stdout_size',
            field=models.IntegerField(blank=True, default=None, help_text="The size in bytes of the student test name discovery command's stdout.\n            None indicates:\n            - The 2025.08.0 output storage compression hasn't been applied to this object\n              (i.e., the output is uncompressed)\n            - The output size should be retrieved from the filesystem\n\n            When non-None, stores the size in bytes of the output and indicates\n            that the output is compressed using LZMA: https://docs.python.org/3/library/gzip.html\n\n            When zero, there will be NO ACTUAL FILE stored in the filesystem\n        ", null=True),
        ),
    ]
