# Generated by Django 5.2.4 on 2025-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_agtestcommandresult_stderr_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stderr_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0. The size in bytes\n        ', null=True),
        ),
        migrations.AddField(
            model_name='agtestcommandresult',
            name='stdout_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0. The size in bytes\n        ', null=True),
        ),
    ]
