# Generated by Django 5.2.4 on 2025-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_agtestcommandresult_stderr_diff_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stderr_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0.\n            The size in bytes of the diff result for this stderr.\n            When None, fall back to the previous logic for computing diff size.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='agtestcommandresult',
            name='stdout_diff_size',
            field=models.IntegerField(blank=True, default=None, help_text='New in 2025.08.0.\n            The size in bytes of the diff result for this stdout.\n            When None, fall back to the previous logic for computing diff size.\n        ', null=True),
        ),
    ]
