# Generated by Django 5.2.4 on 2025-08-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_latedayusage'),
        ('core', '0121_alter_agtestcommandresult_stderr_diff_size_and_more'),
    ]

    operations = [
    ]
