# Generated by Django 5.2.4 on 2025-12-17 15:24

import autograder.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_auto_20250225_1535_squashed_0122_merge_20250801_1924"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="submission_limit_reset_timezone",
            new_name="timezone",
        ),
        migrations.AlterField(
            model_name="project",
            name="timezone",
            field=models.TextField(
                default="UTC",
                help_text="A string representing the timezone to use when storing and\n            comparing dates and times for this project.",
                validators=[autograder.core.utils.validate_timezone],
            ),
        ),
    ]
