# Generated by Django 5.2.4 on 2026-03-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_remove_project_submission_limit_reset_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latedayusage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_day_usages', to='core.course'),
        ),
    ]
