# Generated by Django 5.2.4 on 2026-04-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_latedayusage_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LateDayUsage',
            new_name='LateDayUsageRecord',
        ),
    ]
