# Generated by Django 5.2.4 on 2026-04-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_rename_latedayusage_latedayusagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latedayusagerecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_day_usage_records', to='core.course'),
        ),
    ]
