# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='handgrading.Location'),
        ),
    ]
