# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 18:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingrubric',
            name='max_points',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
