# Generated by Django 2.0.1 on 2018-01-02 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0002_auto_20180102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedannotation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='handgrading.Location'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='handgrading.Location'),
        ),
        migrations.AlterField(
            model_name='handgradingrubric',
            name='max_points',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
