# Generated by Django 2.0.1 on 2018-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0002_results_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedannotation',
            name='comment',
        ),
    ]
