# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0002_auto_20171211_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrarypoints',
            name='handgrading_result',
        ),
        migrations.RemoveField(
            model_name='arbitrarypoints',
            name='location',
        ),
        migrations.RenameField(
            model_name='handgradingrubric',
            old_name='handgraders_can_apply_arbitrary_points',
            new_name='handgraders_can_adjust_points',
        ),
        migrations.AddField(
            model_name='handgradingresult',
            name='points_adjustment',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='ArbitraryPoints',
        ),
    ]
