# Generated by Django 2.0.1 on 2018-01-02 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0003_auto_20180102_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingrubric',
            name='max_points',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
