# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0003_auto_20171221_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='handgradingresult',
            name='finished_grading',
            field=models.BooleanField(default=False),
        ),
    ]
