# Generated by Django 2.0.1 on 2018-01-03 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0004_auto_20180102_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingresult',
            name='points_adjustment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='handgradingrubric',
            name='max_points',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
