# Generated by Django 2.2 on 2019-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0004_rename_handgrading_result_submission_group_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingresult',
            name='finished_grading',
            field=models.BooleanField(blank=True, default=False, help_text="Handgraders should set this field to True when they are finished\n                     grading this group's submission."),
        ),
        migrations.AlterField(
            model_name='handgradingrubric',
            name='handgraders_can_adjust_points',
            field=models.BooleanField(blank=True, default=False, help_text='Whether handgraders can edit HandgradingResult.point_adjustment.'),
        ),
        migrations.AlterField(
            model_name='handgradingrubric',
            name='handgraders_can_leave_comments',
            field=models.BooleanField(blank=True, default=False, help_text='Whether handgraders can add comments to a HandgradingResult.'),
        ),
        migrations.AlterField(
            model_name='handgradingrubric',
            name='show_grades_and_rubric_to_students',
            field=models.BooleanField(blank=True, default=False, help_text='Whether students can see their handgrading scores,\n                     including information from the rubric.'),
        ),
    ]
