# Generated by Django 2.2 on 2019-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0005_auto_20190523_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedannotation',
            old_name='location',
            new_name='old_location',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='location',
            new_name='old_location',
        ),
    ]
