# Generated by Django 2.0.1 on 2018-02-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0005_auto_20180103_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterionresult',
            options={'ordering': ('criterion___order',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='annotation',
            order_with_respect_to='handgrading_rubric',
        ),
        migrations.AlterOrderWithRespectTo(
            name='criterion',
            order_with_respect_to='handgrading_rubric',
        ),
    ]
