# Generated by Django 2.0.1 on 2018-02-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0006_auto_20180211_1527'),
        ('handgrading', '0006_auto_20180215_1107'),
    ]

    operations = [
    ]
