# Generated by Django 2.2 on 2019-05-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0007_add_new_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedannotation',
            name='old_location',
            field=models.OneToOneField(blank=True, default=None, help_text='The source code location where the Annotation was applied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='handgrading.Location'),
        ),
    ]
