# Generated by Django 3.0.5 on 2020-05-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0008_make_old_location_nullable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='appliedannotation',
            name='old_location',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='old_location',
        ),
    ]
