# Generated by Django 3.1.2 on 2020-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0009_remove_legacy_fields_and_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingrubric',
            name='points_style',
            field=models.TextField(blank=True, choices=[('start_at_zero_and_add', 'Start At Zero And Add'), ('start_at_max_and_subtract', 'Start At Max And Subtract')], default='start_at_zero_and_add', help_text='Determines how total_points and total_possible_points are calculated\n                     for HandgradingResults.'),
        ),
    ]
