# Generated by Django 3.2.2 on 2022-10-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0010_replace_enum_field_with_text_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='handgradingrubric',
            name='show_only_applied_rubric_to_students',
            field=models.BooleanField(blank=True, default=False, help_text='Whether students can see rubric items that were not applied to their submission.'),
        ),
    ]
