# Generated by Django 3.2.2 on 2022-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0011_handgradingrubric_show_only_applied_rubric_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingrubric',
            name='show_only_applied_rubric_to_students',
            field=models.BooleanField(blank=True, default=False, help_text='Whether students can see rubric items that\n                     were not applied to their submission.'),
        ),
    ]
