# Generated by Django 5.2.4 on 2026-07-29 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handgrading', '0013_alter_handgradingresult_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingrubric',
            name='max_points',
            field=models.IntegerField(blank=True, default=None, help_text='The denominator of a handgrading score.\n                     When points_style is "start_at_zero_and_add", this value\n                     overrides the sum of positive Criteria point values as the\n                     total points possible.\n                     When points_style is "start_at_max_and_subtract", this field\n                     is REQUIRED.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
