# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='_DummyAutograderTestCase',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.autogradertestcasebase',),
        ),
        migrations.CreateModel(
            name='_DummyCompiledAutograderTestCase',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.compiledautogradertestcase',),
        ),
    ]
