# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='_DummyAutograderTestCase',
            fields=[
                ('autogradertestcasebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AutograderTestCaseBase')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.autogradertestcasebase',),
        ),
        migrations.CreateModel(
            name='_DummyCompiledAutograderTestCase',
            fields=[
                ('compiledautogradertestcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CompiledAutograderTestCase')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.compiledautogradertestcase',),
        ),
    ]
