# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:16
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_autograder_test_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_dummycompiledautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=True),
        ),
    ]
