# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 02:39
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_autograder_test_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_dummycompiledautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++')], max_length=255, strip=True),
        ),
        migrations.AlterField(
            model_name='_dummycompiledautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=True, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
    ]
