# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:19
from __future__ import unicode_literals

import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_autograder_test_case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='_dummycompiledautogradertestcase',
            name='files_to_compile_together',
        ),
        migrations.AddField(
            model_name='_dummycompiledautogradertestcase',
            name='project_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
        migrations.AddField(
            model_name='_dummycompiledautogradertestcase',
            name='student_files_to_compile_together',
            field=autograder.utilities.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=False),
        ),
    ]
