# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 00:42
from __future__ import unicode_literals

import autograder.core.shared.utilities
import autograder.utilities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_autograder_test_case', '0002_auto_20160214_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_dummycompiledautogradertestcase',
            name='compiler',
            field=autograder.utilities.fields.ShortStringField(choices=[('g++', 'g++'), ('clang++', 'clang++'), ('gcc', 'gcc'), ('clang', 'clang')], max_length=255, strip=False),
        ),
        migrations.AlterField(
            model_name='_dummycompiledautogradertestcase',
            name='executable_name',
            field=autograder.utilities.fields.ShortStringField(default='compiled_program', max_length=255, strip=False, validators=[autograder.core.shared.utilities.check_user_provided_filename]),
        ),
    ]
