# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autogradertestcasebase',
            old_name='points_for_no_valgrind_errors',
            new_name='deduction_for_valgrind_errors',
        ),
    ]
