# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 20:46
from __future__ import unicode_literals

import autograder.fields
import autograder.shared.feedback_configuration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_auto_20151213_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogradertestcasebase',
            name='hide_from_students',
        ),
        migrations.AddField(
            model_name='autogradertestcasebase',
            name='feedback_configuration',
            field=autograder.fields.JsonSerializableClassField(class_=autograder.shared.feedback_configuration.AutograderTestCaseFeedbackConfiguration, default=autograder.shared.feedback_configuration.AutograderTestCaseFeedbackConfiguration),
        ),
    ]
