# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_auto_20151213_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutograderTestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_code', models.IntegerField(default=None, null=True)),
                ('standard_output', models.TextField()),
                ('standard_error_output', models.TextField()),
                ('timed_out', models.BooleanField(default=False)),
                ('valgrind_return_code', models.IntegerField(default=None, null=True)),
                ('valgrind_output', models.TextField()),
                ('compilation_return_code', models.IntegerField(default=None, null=True)),
                ('compilation_standard_output', models.TextField()),
                ('compilation_standard_error_output', models.TextField()),
                ('submission', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autograder.Submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autograder.AutograderTestCaseBase')),
            ],
        ),
        migrations.RemoveField(
            model_name='autogradertestcaseresultbase',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='autogradertestcaseresultbase',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='autogradertestcaseresultbase',
            name='test_case',
        ),
        migrations.DeleteModel(
            name='AutograderTestCaseResultBase',
        ),
    ]
