# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:38
from __future__ import unicode_literals

import autograder.fields
import autograder.models.autograder_test_case.autograder_test_case_base
import autograder.shared.utilities
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0003_auto_20151213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='command_line_arguments',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[autograder.models.autograder_test_case.autograder_test_case_base._validate_cmd_line_arg], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='compiler',
            field=autograder.fields.ShortStringField(blank=True, choices=[('g++', 'g++')], strip=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='compiler_flags',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[autograder.models.autograder_test_case.autograder_test_case_base._validate_cmd_line_arg], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='executable_name',
            field=autograder.fields.ShortStringField(blank=True, strip=True, validators=[autograder.shared.utilities.check_user_provided_filename]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='files_to_compile_together',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='name',
            field=autograder.fields.ShortStringField(strip=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='student_resource_files',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=[], max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='test_resource_files',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=[], max_string_length=255, size=None, string_validators=[], strip_strings=True),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='time_limit',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='autogradertestcasebase',
            name='valgrind_flags',
            field=autograder.fields.StringArrayField(allow_empty_strings=False, blank=True, default=list, max_string_length=255, size=None, string_validators=[autograder.models.autograder_test_case.autograder_test_case_base._validate_cmd_line_arg], strip_strings=True),
        ),
    ]
