from .course_views.course_view import CourseViewSet
from .course_views.course_admins import CourseAdminViewSet
from .course_views.course_staff import CourseStaffViewSet
from .course_views.course_enrolled_students import CourseEnrolledStudentsViewset
from .course_views.course_projects import CourseProjectsViewSet

from .project_views.project_view import ProjectViewSet
from .project_views.project_expected_student_file_patterns import (
    ProjectExpectedStudentFilePatternsViewSet)
from .project_views.project_uploaded_files import ProjectUploadedFilesViewSet
from .project_views.project_groups import ProjectGroupsViewSet
from .project_views.project_ag_test_cases import ProjectAGTestsViewset
from .project_views.project_group_invitations import ProjectGroupInvitationsViewset

from .expected_student_file_pattern_view import ExpectedStudentFilePatternViewset
from .uploaded_file_views import UploadedFileViewset
