from .oauth2callback import oauth2_callback

from .user_views import UserViewset

from .course_views.course_view import CourseViewSet
from .course_views.course_admins import CourseAdminViewSet
from .course_views.course_staff import CourseStaffViewSet
from .course_views.course_enrolled_students import CourseEnrolledStudentsViewset
from .course_views.course_projects import CourseProjectsViewSet

from .project_views.project_view import ProjectViewSet
from .project_views.project_expected_student_file_patterns import (
    ProjectExpectedStudentFilePatternsViewSet)
from .project_views.project_uploaded_files import ProjectUploadedFilesViewSet
from .project_views.project_groups import ProjectGroupsViewSet
from .project_views.project_ag_test_cases import ProjectAGTestsViewset
from .project_views.project_group_invitations import ProjectGroupInvitationsViewset

from .expected_student_file_pattern_views import ExpectedStudentFilePatternViewset
from .uploaded_file_views import UploadedFileViewset
from .ag_test_case_views import AGTestCaseViewset
from .group_invitation_views import GroupInvitationViewset

from .group_views.group_view import GroupViewset
from .group_views.group_submissions_view import GroupSubmissionsViewset

from .submission_views.submission_view import SubmissionViewset
from .submission_views.submission_results import SubmissionResultsViewset

# from .ag_test_result_views import AGTestResultViewSet
