name: Autograder Server

on:
  push:
    branches: [ develop, release* ]
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
        required: true

jobs:
  lint:
    runs-on: ubuntu-24.04

    # update-version-number only does anything on workflow_dispatch
    needs: update-version-number

    strategy:
      matrix:
        python-version: ["3.10"]
        node-version: [16.x]

    services:  # Required for checking migrations and schema
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip==24.0
          python -m pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
          python3 generate_secrets.py
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint code style, type check, check migrations are up to date, validate schema
        run: |
          bash lint.sh

  test:
    runs-on: ubuntu-24.04
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip==24.0
          python -m pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
          python3 generate_secrets.py
      - name: Run tests
        run: |
          python3 manage.py test -v2 --exclude-tag fix_on_ci --exclude-tag slow --exclude-tag sandbox

  slow_tests:
    runs-on: ubuntu-24.04
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip==24.0
          python -m pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
          python3 generate_secrets.py
      - name: Run tests
        run: |
          python3 manage.py test -v2 --exclude-tag fix_on_ci --tag slow --tag sandbox

  # Runs only on workflow_dispatch
  update-version-number:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Update version number (on tag only)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            echo Version: "${{ inputs.version }}"
            ./dev_scripts/update_version_number.sh "${{ inputs.version }}"
          else
            echo "Not a workflow dispatch. Skipping version update."
          fi

      - name: Upload updated version files
        uses: actions/upload-artifact@v4
        with:
          name: updated-version-files
          path: |
            autograder/settings/base.py
            autograder/rest_api/schema/schema.yml

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    if: github.event_name == 'workflow_dispatch'

    # needs:
    # - lint
    # - test
    # - slow_tests

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Download updated version files
        uses: actions/download-artifact@v4
        with:
          name: updated-version-files

      - name: Commit updated version files
        run: |
          git add autograder/settings/base.py autograder/rest_api/schema/schema.yml
          git commit -m "Version ${{ inputs.version }}"
          git push --dry-run
          git tag ${{ inputs.version }}
          git push --dry-run --tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes ""
